### ISSUE TITLE
Configuration of kubelet daemon arguments

### ISSUE THREAD

**Issue by Zetten** [puppetlabs/puppetlabs-kubernetes#100]
I might have overlooked this, but is there a way in this module to configure and pass extra arguments to the kubelet service?

For example, I have edited `/etc/systemd/system/kubelet.service.d/override.conf` to start the kubelet server with an additional authentication method:
```
[Service]
Environment="KUBELET_EXTRA_ARGS=--authentication-token-webhook"
```

I'm not sure all such parameters can be managed solely in `kubelet.conf`.

I would try and raise a PR but I'm not sure of the conventional way to override systemd units via Puppet.

**Comment by scotty-c** [comment]
@Zetten there is a new release that is just waiting on QA sign off that will fix this

**Comment by davejrt** [comment]
@Zetten additional arguments for the kubelet are now available via the config file that we use when we exec kubeadm init --config
