### ISSUE TITLE
Bootstrap controller - check if cni provider has been installed?

### ISSUE THREAD

**Issue by esalberg** [puppetlabs/puppetlabs-kubernetes#103]
## Versions:
```
$ puppet --version = 4.7.0

$ kubectl version = 1.9.7

$ docker version OR crictl version = 17.03.0-ce

$ facter os = RHEL 7.4

```

It looks like the main reason that the bootstrap_controller flag has to be manually turned off after bootstrap is because there's no gate on the following exec:

    exec { 'Install cni network provider':
      command => "kubectl apply -f ${cni_network_provider}",
      onlyif  => 'kubectl get nodes',
      }

I was looking into possible ways to be able to tell if the network provider is applied, but I am only working with weave currently, and I'm sure that coverage for flannel and calico would be needed as well.

Is it sufficient to check if there's a file under /etc/cni/net.d (e.g. 10-weave.conf)?  If so, I'm happy to put in a PR, but I'd need to know the file names for flannel / calico.

If not, is there a suggestion as to what to investigate, or is it unlikely that an attempted solution will get accepted (or is someone else already looking at it)?

**Comment by scotty-c** [comment]
@esalberg kubernetes can tell you this through the cluster state. 
What is the issue you are seeing that you need this functionality.

**Comment by esalberg** [comment]
Right now, if you leave bootstrap_controller set to true, it reinstalls the cni provider every run.

I know the documentation says to set bootstrap_controller to false after bootstrapping is done, but it would be really nice not to have to do that.

**Comment by vinixavier** [comment]
Up @esalberg 
Here happens too.

**Comment by scotty-c** [comment]
@esalberg and @vinixavier this has been fixed in the next release.

**Comment by scotty-c** [comment]
Closing due to #106 being released
