### ISSUE TITLE
Missing puppet/kubetool:2.0.0 docker image

### ISSUE THREAD

**Issue by pelacables** [puppetlabs/puppetlabs-kubernetes#111]
According to the project documentation the version of kubetool you use must match the version of the module on the Puppet Forge.  Current forge version is 2.0.2 👍 

![image](https://user-images.githubusercontent.com/3243310/40917250-d69e1a3a-6802-11e8-8f2b-4f61b8c43b12.png)

## What you expected to happen?

Docker image pulled from the repository

## What happened?

Image cannot be found:
```bash
Unable to find image 'puppet/kubetool:2.0.2' locally
Pulling repository docker.io/puppet/kubetool
docker: Tag 2.0.2 not found in repository docker.io/puppet/kubetool.
```
## How to reproduce it?
Run 
```bash
docker run --rm -v $(pwd):/mnt --env-file .env puppet/kubetool:2.0.2
```

$ docker --version
Docker version 1.11.2, build b9f10c9

**Comment by scotty-c** [comment]
@pelacables The new version of the image `puppet/kubetool:2.0.2` is on Docker Hub
