### ISSUE TITLE
Support for using existing etcd

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppetlabs/puppetlabs-kubernetes#121]
I was looking at using this module to bootstrap my kubernetes cluster, but does not setup RBAC in etcd, and it does not support setting etcd up in SSL only mode.
i am using cristifalcos/puppet-etcd - and if this module could have an option for using an existing etcd, that would be most useful.

**Comment by scotty-c** [comment]
@KlavsKlavsen we are not going to add a dependency to an external etcd module. The reason for this is support.  Also this module only supports etcd with ssl, it will not work without SSL. What ssl options are missing ?

**Comment by KlavsKlavsen** [comment]
I wasn't talking about adding a dependency to an external module - more the option of using an existing etcd cluster (which I could then setup with a diff. module if I wanted to).

**Comment by scotty-c** [comment]
@KlavsKlavsen that still leaves us with a support issue that I mentioned earlier. This module is supported and if there is an issue with your cluster all the settings are within this module which allows us to support it, if you have any issues in which the kube API server does not start due to the configuration of the external etcd server. How can we support that without a lot of troubleshooting?

**Comment by KlavsKlavsen** [comment]
well then atleast support using a package instead of downloading an older version of etcd ?
Ubuntu 18.04 has 3.2.17

**Comment by KlavsKlavsen** [comment]
and just as you depend on other modules for some things (and choose NOT to depend on docker because it was JUST a simple package) - one could argue that you could have an optional dependency for the etcd module I suggest - which supports using Ubuntu 18.04's etcd package and sets it up. Testing it that works or not - is fairly easy, by just calling with with etcd-client.

**Comment by KlavsKlavsen** [comment]
None of our servers that run public websites - have internet access. (for good reason - if a security flaw is found - the most likely place to find a "canary" - is by blocking traffic to internet - and watching those logs (they should be empty). This is why we have mirrors of everything we use - and package everything. I f.ex. package kubernetes releases - and would like module to support using packages to install things, instead expecting all servers to have internet access.

**Comment by khaefeli** [comment]
totally agree with @KlavsKlavsen 

=> @scotty-c another point is the param $etcd_version.
I'd expect that if I set a version, then puppet brings my machine into this state.
With the archive / exec approach you can't upgrade without manually removing the binary.

2) Personally I also want to keep my system clean / minimal (e.g. without wget and 3rd party puppet modules)
3) with package you already have a powerful provider for installations maintained by puppetlabs.
only define the package and that's it..
4) there are other security aspects: package signing keys

**Comment by scotty-c** [comment]
@khaefeli, not all OS vendors have etcd packages and if they do they don't have all the versions. For example, Ubuntu 16.04 only has 2.2.5. So what would be the suggestion to for those users?

**Comment by KlavsKlavsen** [comment]
@scotty-c To NOT tell kubernetes module that they already have an ETCD cluster they want it to use - and your module would do its default - to setup etcd itself :)

**Comment by scotty-c** [comment]
@khaefeli We are not going to change the module to be able to manage etcd externally as mentioned earlier in the conversation. 

I think it is unreasonable to tell people to upgrade there OS to support the etcd version with Puppet when that is not required upstream by Kubernetes or Kubeadm. 

There are features that will address some of  the issues in next release we will fix
