### ISSUE TITLE
Fails on Xenial

### ISSUE THREAD

**Issue by KlavsKlavsen** [puppetlabs/puppetlabs-kubernetes#123]
I tested out kubernetes module - just vanilla. (latest master), and it fails in kubeadm init with:

 [init] Using Kubernetes version: v1.10.5
.. (above - even though settings say to use 1.10.2)
Kubeadm_init.. [markmaster] Will mark node kube-cam02 as master by adding a label and a taint
error marking master: timed out waiting for the condition

I am assuming its because kube-cam02 points (in hosts file) to 127.0.0.1 and service is only listening on public ip ?

I ran tooling to get config with these options:
docker run --rm -v $(pwd):/mnt -e OS=debian -e VERSION=1.10.2 -e CONTAINER_RUNTIME=docker -e CNI_PROVIDER=calico -e ETCD_INITIAL_CLUSTER=kube-cam01.example.org:192.168.63.198,kube-cam02.example.org:192.168.63.199,kube-cam03.example.org:192.168.63.200 -e ETCD_IP="%{::ipaddress_ens192}" -e KUBE_API_ADVERTISE_ADDRESS="192.168.63.29" -e INSTALL_DASHBOARD=true puppet/kubetool:2.0.2

I also had to fix two things to even get this far.
1. change https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/templates/etcd/etcd.service.erb#L14 from $hostname to $fqdn  - otherwise etcd would not start.
2. after that I had to manually install crictl - by doing: apt-get install cri-tools

and then I landed at the above error..

**Comment by KlavsKlavsen** [comment]
and having $hostname as default is IMHO a security issue, as it relies on your domain search pattern on client (as rendered by dhcp often). If I add a kube-cam01.example2.org - and your search has both domains (and example2 first - or I manipulate dhcp response or.. ) - I will reach kube-cam01.example2.org - and SSL will be perfectly happy - as certificate ONLY has hostname part..
One should always use FQDN's in certificates.

**Comment by KlavsKlavsen** [comment]
Changing settings to:
docker run --rm -v $(pwd):/mnt -e OS=debian -e VERSION=1.10.2 -e CONTAINER_RUNTIME=docker -e CNI_PROVIDER=calico -e ETCD_INITIAL_CLUSTER=kube-cam01:192.168.63.198,kube-cam02:192.168.63.199,kube-cam03:192.168.63.200 -e ETCD_IP="%{::ipaddress_ens192}" -e KUBE_API_ADVERTISE_ADDRESS="192.168.63.29" -e INSTALL_DASHBOARD=true puppet/kubetool:2.0.2

Made cluster setup work for the masters.. but the workers fail to join:
[kubeadm join]/returns:        [ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: fork/exec /usr/bin/crictl -r /var/run/dockershim.sock info: no such file or directory


and on masters it does not look "entirely ok": kubectl get pods --all-namespaces
NAMESPACE     NAME                                                  READY     STATUS             RESTARTS   AGE
kube-system   calico-etcd-9q76n                                     1/1       Running            0          17m
kube-system   calico-etcd-j9mgw                                     1/1       Running            0          17m
kube-system   calico-etcd-lr4z6                                     1/1       Running            0          17m
kube-system   calico-kube-controllers-79dccdc4cc-5kxph              1/1       Running            1          17m
kube-system   calico-node-6p6g6                                     2/2       Running            0          17m
kube-system   calico-node-cz48n                                     1/2       CrashLoopBackOff   7          17m
kube-system   calico-node-w52pt                                     2/2       Running            1          17m
kube-system   kube-apiserver-p-boa-kube-cam01.yousee.idk            1/1       Running            0          16m
kube-system   kube-apiserver-p-boa-kube-cam02.yousee.idk            1/1       Running            0          16m
kube-system   kube-apiserver-p-boa-kube-cam03.yousee.idk            1/1       Running            0          16m
kube-system   kube-controller-manager-p-boa-kube-cam01.yousee.idk   1/1       Running            0          17m
kube-system   kube-controller-manager-p-boa-kube-cam02.yousee.idk   1/1       Running            0          18m
kube-system   kube-controller-manager-p-boa-kube-cam03.yousee.idk   1/1       Running            0          16m
kube-system   kube-dns-86f4d74b45-bp2b9                             1/3       CrashLoopBackOff   18         17m
kube-system   kube-proxy-dcmw7                                      1/1       Running            0          17m
kube-system   kube-proxy-v2d2c                                      1/1       Running            0          17m
kube-system   kube-proxy-w9x72                                      1/1       Running            0          17m
kube-system   kube-scheduler-p-boa-kube-cam01.yousee.idk            1/1       Running            0          16m
kube-system   kube-scheduler-p-boa-kube-cam02.yousee.idk            1/1       Running            0          17m
kube-system   kube-scheduler-p-boa-kube-cam03.yousee.idk            1/1       Running            0          17m
kube-system   kubernetes-dashboard-7d5dcdb6d9-r5jmz                 0/1       CrashLoopBackOff   6          17m

(note: worker is Ubuntu 18.04/bionic)

**Comment by davejrt** [comment]
Can you please create a gist with your hiera file that's being produced?

**Comment by KlavsKlavsen** [comment]
https://gist.github.com/KlavsKlavsen/7b3a3d8e0e3796097cbaf69d4493890a (the Debian.yaml file)

**Comment by davejrt** [comment]
I've tested with the same config, including IP range without any issues using the version from the forge and master. 

If you can create the cluster from scratch and recreate the problem can you send all the info, including puppet logs that we request in the template for issues? It's difficult without complete logs. I generally sometimes see errors relating to cri if etcd doesn't start. Regarding the k8s version I think you'll find that despite the log saying it's 1.10.5 when you list the nodes using `kubectl get nodes` they will say 1.10.2

**Comment by KlavsKlavsen** [comment]
the node list says 1.10.2.. It must be some "detail" in my xenial setup then or something.

I instead wrote a puppet module using kelsey hightowers approach (ie. not kubeadm - but instead writing config files directly and not using hyperkube) - so I'll just continue down that path for now. Kubeadm is interesting - but I think I'll prefer actually knowing how the configs should look for the few kubernetes services needed..

**Comment by davejrt** [comment]
It's probably worth noting that the previous version of this module used a similar approach, however the feedback we received was that it was too hard to use. In addition to that it became difficult to maintain each release cycle. We moved to kubeadm as now we're protected from a lot of that by installing an upstream distro rather than hand rolling our own.

Thanks for the feedback
