### ISSUE TITLE
Upgrade module dependencies version

### ISSUE THREAD

**Issue by lzecca78** [puppetlabs/puppetlabs-kubernetes#124]
Hi guys, i would like to adopt this module but i have newer version of some other module that are currently used by yours: 

`{"name":"puppetlabs-apt","version_requirement":">= 4.1.0 < 4.3.0"}`
`{"name":"puppet-archive","version_requirement":">= 2.0.0 < 2.1.0"}`

Is there any reason why both are strictly necessary to those versions? I am currently using them in my project and both are set to version greater than yours ( `mod 'puppetlabs-apt', '4.5.1'`, `mod 'puppet-archive', '2.2.0'`), so when i try to add them, librarian-puppet is not able to satisfy dependencies. 
Can you set a larger version interval in order to let use your module to those that have a newer version of modules? Thanks!

**Comment by davejrt** [comment]
fixed in pr #125
