### ISSUE TITLE
Make yum repo creation optional?

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#128]
The repos used by this Kubernetes module are hardcoded in the file repos.pp. Unfortunately, I am installing Kubernetes in an environment where we can't easily get out to the internet. For other applications, we've simply mirrored the repos internally, and provided our own yumrepo commands.

Would it be possible to make the yumrepo creations optional, or overrideable?  The way the code is now, installing this module completely messes up all yum interactions, because the two yum repos entries (one for docker, one for kubernetes) provide baseurl entries that are unreachable by the host.

**Comment by davejrt** [comment]
@vrmerlin you can now disable the creation of the repos, or choose to override them after the commits in #133
