### ISSUE TITLE
etcd service start timeout

### ISSUE THREAD

**Issue by khaefeli** [puppetlabs/puppetlabs-kubernetes#138]
## What you expected to happen?
if the service hangs, don't wait for the etcd service during the puppet run.

## What happened?
if my etcd service can't start, the puppet runs waits forever because of TimeoutStartSec=0
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/templates/etcd/etcd.service.erb#L12

official service file:
https://github.com/coreos/etcd/blob/master/contrib/systemd/etcd.service

## How to reproduce it?
configure some wrong hostnames for `kubernetes::etcd_initial_cluster:` which let etcd fail.

## Versions:
$ puppet --version
4.10.12
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

$ docker version
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```
$ facter os
```
{
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.5 (stretch)",
    id => "Debian",
    release => {
      full => "9.5",
      major => "9",
      minor => "5"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.5",
    major => "9",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}
```
Systemd version: 237-3~bpo9+1

**Comment by scotty-c** [comment]
@khaefeli can you fill in the rest of the issue template please

**Comment by scotty-c** [comment]
@khaefeli I have just tested this with both Ubuntu and RHEL and did not see this issue. The service failed to start instantly due to not being able to connect to the initial cluster. what version of systemd are you running?

**Comment by spali** [comment]
Probably it's a Debian specific thing, I had the same on all three controllers hanging at
```
Notice: /Stage[main]/Kubernetes::Service/Service[etcd]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Kubernetes::Service/Service[etcd]: Unscheduling refresh on Service[etcd]
``` 
In my case the hostnames are correct.
But etcd had a lot of timeouts in the log (I have to say, that my test cluster is a bit low powered on resources). So I had tls handshake errors due clock difference more than 1 seconds between the peers and also i/o timeouts.

So I think the reason for hanging could differ. But as long as etcd is not fully up, the puppet run hangs.
As soon as I had improved the performance and my clock's where running in a green range, the puppet run continued because etcd started successfully.

`systemd                       232-25+deb9u4`

**Comment by blodone** [comment]
we encountered the same issue with local kitchen test setup. only if all controller nodes are provisioned the same time in parallel the run continues. otherwise if one node is not setup it hangs forever

**Comment by carabasdaniel** [comment]
Hello @blodone,
Closing this issue as it has been from a very old version of the module. If the problem persists please feel free to re-open and add more recent information. 
Thanks.
