### ISSUE TITLE
Containerd service: don't exec modprobe overlay

### ISSUE THREAD

**Issue by khaefeli** [puppetlabs/puppetlabs-kubernetes#145]
## What you expected to happen?
we don't want the containerd service running `/sbin/modprobe overlay` on systems where `$::is_virtual ==  true` 

## What happened?
the service tries to load the overlay kernel module. 
this doesn't work, because e.g. on LXC the kernel modules are managed on the hostserver.
and the service start fails:

```
Aug 09 14:10:12 kube-controller2 modprobe[28618]: modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.16.0-0.bpo.2-amd64/modules.builtin.bin'
Aug 09 14:10:12 kube-controller2 modprobe[28618]: modprobe: FATAL: Module overlay not found in directory /lib/modules/4.16.0-0.bpo.2-amd64
Aug 09 14:10:12 kube-controller2 systemd[1]: containerd.service: Control process exited, code=exited status=1
Aug 09 14:10:12 kube-controller2 systemd[1]: Failed to start containerd container runtime.
```

## How to reproduce it?
Setup a lxc container, install the kubernetes controller with containerd.

## Anything else we need to know?
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/templates/containerd.service.erb#L7
make the template configurable and e.g. check for the is_virtual fact

## Versions:
$ puppet --version
4.10.12
$ kubectl version
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```

$ docker version
```
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:33 2018
 OS/Arch:           linux/amd64
 Experimental:      false
```
$ facter os
```
{
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.5 (stretch)",
    id => "Debian",
    release => {
      full => "9.5",
      major => "9",
      minor => "5"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.5",
    major => "9",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}
```
$ containerd version
``` 
containerd github.com/containerd/containerd v1.1.0 209a7fc3e4a32ef71a8c7b50c68fc8398415badf
```

**Comment by davejrt** [comment]
We run this code in vagrant a lot, which has that fact set to true, and don't get this error. I'm not aware that the version of docker you're running is officially supported in 1.11.0 either

**Comment by khaefeli** [comment]
@davejrt thank you for your answer. 
are you also using `containerd` as runtime instead of `docker`? 
which kind of virtualization is vagrant using?

there is actually no code in the manifests, which take care of `is_virtual`. 
That was my proposal how to fix the issue :)

**Comment by davejrt** [comment]
I'm confused, are you using docker or containerd as the runtime? You've pasted in an unsupported docker version above. 

Can you provide more information about the environment you're seeing this issue on so we can determine whether or not this isn't isolated to your combination of software versions and virutal environment.

**Comment by khaefeli** [comment]
@davejrt: I'm using `containerd` as runtime. Sorry, for the confusion. I've missed the version command there for containerd (I've updated the initial report now)

Environment:
3 bare metal servers with:
- Kernel 4.17 (linux-image-4.17.0-0.bpo.1-amd64)
- Debian Stretch (9.5)
- LXC 2.0.7-2+deb9u2
- lxcfs 2.0.7-1

The Kubernetes controllers are running inside a LXC container on each host.
Every bare metal (host) has 1x controller (lxc container) 1x worker (2nd container):
$ lxc-ls
```
kube-controller2 
kube-worker2  
```
with the relevant kubernetes containers lxc config:

 ```
lxc.include = /usr/share/lxc/config/nesting.conf
lxc.include = /usr/share/lxc/config/debian.common.conf
lxc.mount.auto=proc:rw sys:rw
lxc.aa_profile=unconfined
lxc.cgroup.devices.allow=a
```
(apparmor disabled / unconfined) 

Networking: weave

To point out: the issue is the modprobe command on a lxc guest-machine.
This should never work, because it would be a huge security issue if lxc guests could load kernel module on the host (lxc machines share the kernel with the host)

**Comment by davejrt** [comment]
Closing as this issue is beyond the scope of this module
