### ISSUE TITLE
Etcd version 3.1.12 always gets installed, even when overriden

### ISSUE THREAD

**Issue by jonasdemoor** [puppetlabs/puppetlabs-kubernetes#151]
## What you expected to happen?

I expected the module to install version 3.2.18 of Etcd instead of the default version (3.1.12).

## What happened?

Version 3.1.12 is installed instead of the specified version.

## How to reproduce it?

I tried overriding it via Hiera and by directly declaring the class.

Hiera:
```yaml
kubernetes::etcd_version: 3.2.18
```
Puppet:
```puppet
class  { 'kubernetes':
    controller             => true,
    manage_docker          => true,
    etcd_version           => '3.2.18',
    docker_version         => '17.03.0~ce-0~debian-stretch',
    docker_apt_release     => 'stretch',
    docker_apt_repos       => 'stable',
    docker_apt_location    => 'https://download.docker.com/linux/debian',
    docker_package_name    => 'docker-ce',
    kubernetes_apt_release => 'kubernetes-xenial',
  }
```
## Anything else we need to know?

I'm trying to set up a Kubernetes cluster with one master node on a local Vagrant environment.  I bumped into this problem when trying to set up Kubernetes 1.11.0; this version of Kubernetes needs Etcd >= 3.2.17.
Installing Etcd 3.2.18 has always worked in the past.

## Versions:

```
$ puppet --version
4.10.12
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
$ docker version OR crictl version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:02:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:02:23 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ facter os
{
  architecture => "amd64",
  distro => {
    codename => "stretch",
    description => "Debian GNU/Linux 9.4 (stretch)",
    id => "Debian",
    release => {
      full => "9.4",
      major => "9",
      minor => "4"
    }
  },
  family => "Debian",
  hardware => "x86_64",
  name => "Debian",
  release => {
    full => "9.4",
    major => "9",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}
$ puppet module list
<empty>
```

**Comment by jonasdemoor** [comment]
I first noticed this when trying to bootstrap a cluster on our production systems, but I managed to reproduce it on a local Vagrant box. The info above is of the Vagrant environment.

**Comment by jonasdemoor** [comment]
@davejrt Thank you for your response. I hardcoded the archive and source URL and it works like a charm. 
I might open a PR with a proposal for cleaning things up a bit. I was thinking about adding a flag for enabling/disabling the management of Etcd via this module

**Comment by davejrt** [comment]
I'm going to close this issue, any further discussions we can have on the community slack or a PR.
