### ISSUE TITLE
Improve Readme documentation with more assumptions and detailed instructions

### ISSUE THREAD

**Issue by jdub55** [puppetlabs/puppetlabs-kubernetes#16]
While visiting at a customer site who is trying out this new module, they commented that the current documentation has some room for improvement to make it easier to get up and started with this module. Specifically, all assumptions re: which OS(es) are being used to which directory commands are expected to be run in would be very helpful additions. I've provided a couple specific examples below:

1) The section "Setup Requirements" references required software that needs to be installed. I would recommend breaking this up into separate sections labelled "Software Pre-requisites" and "Setup Requirements". The "Setup Requirements" section would then list out the OS version(s) that these steps have been tested on. And the "Software Pre-requisites" would cover off any software that needs to be installed prior to starting the core kubernetes configuration work. For example, there were some questions around particular versions of Go and Ruby that need to be installed on RHEL 7.2. If there are specific version(s) of this software required it would be helpful to call this out in a special note, etc. and not just refer to the external documentation.

2) In general, provide more detail on steps that are listed. For example, there is reference to running a "bundle install" command under setup but as the instructions are embedded inline in the   sentence, it's not immediately clear that this is a specific script to run. I would recommend breaking out the commands to be run into a separate indented section like the following:

a. Install cfssl by following the documentation _here_.
b. 'cd <module path>' (would be helpful to include an actual example of a default module path)
c. run './bundle install' (?)
d. 'cd '<module path>/tools' (again, a specific example would be helpful here)
e. run './kube_tool' and confirm the following output:

<example output of kube_tool>

The above is just an example but the comment applies generally to the entire README file.

**Comment by scotty-c** [comment]
@jdub55 This is now been updated in PR #22

So hopefully this fix all the issues you raised with the README etc
