### ISSUE TITLE
Multimaster?

### ISSUE THREAD

**Issue by BarnumD** [puppetlabs/puppetlabs-kubernetes#160]
I'm trying to use this module to build a 3-node multi master kubernetes environment.  However, I'm confused about some of the values to put into the initial .env file.  It's not clear whether it's expecting a single ip, or multiple, or even how to format them.  I'm getting errors like this when trying to do a puppet run:
`invalid value "https://1.2.3.4,1.2.3.5,1.2.3.6:2379" for flag -listen-client-urls: URL address does not have the form "host:port": https://1.2.3.4`
It seems like it should only have one IP.  But how can I configure multiple master nodes?

**Comment by nickperry** [comment]
--listen-client-urls should indeed only have a single IP - specific to each master.

This is set using hiera value kubernetes::etcd_ip. Mine is

kubernetes::etcd_ip: "%{::ipaddress_eth0}"

which means that each one of my etcd servers listens on its eth0 IP.

**Comment by davejrt** [comment]
@nickperry is correct, each etcd server listens on it's own individual IP. Under the https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/README.md#generating-the-module-configuration section in the readme there is an example of the values required, where you can change IP addresses and facts for your environment. 

If you're not familiar with some of this I'd recommended looking at the [kream](https://github.com/puppetlabs/kream) repo which includes a vagrant file to setup a multi master environment that may help you.

**Comment by davejrt** [comment]
I'm going to close this, as there is sufficient advice in the documentation provided in this repo, as well as working examples in KREAM to get this up and running. Feel free to re-open or create a new issue if you into more issues once the correct config is being used.
