### ISSUE TITLE
Default structure doesn't inherit correctly

### ISSUE THREAD

**Issue by temujin9** [puppetlabs/puppetlabs-kubernetes#169]
## What you expected to happen?
A change to ```etcd_version``` should update the ```etcd_archive``` and ```etcd_source``` to correct derived values.

## What happened?
The derived values are constructed too early in the process. Unless they are overridden as well, the old version of etcd is installed from the old etcd_source.

## How to reproduce it?
Set etcd_archive in hiera, and compare to the version installed.

## Anything else we need to know?
I'm testing code to fix this, and can build a PR for it (unless you're already fixing it).

## Versions:
```
$ puppet --version
5.5.6

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

$ docker version OR crictl version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:05:44 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ facter os
{
  architecture => "x86_64",
  distro => {
    codename => "Core",
    description => "CentOS Linux release 7.5.1804 (Core)",
    id => "CentOS",
    release => {
      full => "7.5.1804",
      major => "7",
      minor => "5"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

$ puppet module list
/opt/puppetlabs/puppet/modules (no modules installed)
```

**Comment by temujin9** [comment]
@davejrt @scotty-c: I have a fix for my issues in the https://github.com/temujin9/puppetlabs-kubernetes/tree/neliot-fix-param-inheritance branch. However, this fix eliminates kubernetes::params (whose invocation order was causing the defaulting problem). Can you look at it, and tell me if that kind of fix is acceptable, and if not maybe suggest a different approach?

**Comment by SimonHoenscheid** [comment]
I also trembled on this, my fix was to move the version var and the two depending to the main class, keeping the rest in the params

**Comment by davejrt** [comment]
@temujin9 I am happy to look at a PR that brings the data back into the module as is suggested in the best practices now.

**Comment by temujin9** [comment]
Ah, good to hear. I'm at a conference early this week, but I should be able to bang this out Thursday or Friday when I get back. The refactor is done, it's just the tests that need writing.

**Comment by temujin9** [comment]
Ah, turns out my fix takes no correction at all. The test failures occur under the new default puppet version of 6.0.2, with or without my changes.

Setting PUPPET_GEM_VERSION="~> 5.5.7" makes test pass both before and after my change. I'll PR shortly, and then ticket this 6.0.2 issue (which is not a priority from our perspective).

**Comment by temujin9** [comment]
Actually, I notice that the most recent master is now pinned to 5.5.6, so I suspect you already know the issue. Let me know if you want me to ticket it.
