### ISSUE TITLE
Support Ubuntu 18.04 Bionic

### ISSUE THREAD

**Issue by BarnumD** [puppetlabs/puppetlabs-kubernetes#172]
I think this module needs to be updated to support Ubuntu 18.  The apt repositories for both Docker and Kubernetes don't seem to work for this version.  Both repositories have change their structure and location since version 16.04.

**Comment by scotty-c** [comment]
@BarnumD What kubernetes repo are you referring too? We are using https://packages.cloud.google.com/apt/dists

**Comment by BarnumD** [comment]
Right so if you use that repo it doesn't have support for bionic.  If you go there - you'll see there's no entry for `kubernetes-bionic`.  Instead, I had to force it back to xenial (`kubernetes::kubernetes_apt_release: 'kubernetes-xenial'`)

You may also need to double check docker, which i was having trouble with (sorry, I don't have the errors.)  I just wound up bypasing it with `kubernetes::manage_docker: false`.  The download.docker.com repo seems to support bionic, however.

**Comment by davejrt** [comment]
@scotty-c and I looked into this, and until such time as the k8s documentation officially states that 18.04 is supported, and upstream repos are created, we'll be keeping this module supported at 16.04. 

There were a number of comprimes that need to be made, including having to use unsupported docker versions that at stage we don't want to make available in this module.
