### ISSUE TITLE
Adding Cri-o  support

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-kubernetes#177]
My Company is using this module and we use crio as container runtime, I did a bunch of patches and would be happy to add the support to the module. Due to mentions this module is internally under heavy reconstruction, let me know if its currently a good point to file such a big PR.

**Comment by scotty-c** [comment]
@SimonHoenscheid we already support the cri plugin. What functionality does that not give you that cri-o will ?

**Comment by dal00** [comment]
What do you mean when you say the "cri plugin"? My understanding is that you support cri_containerd, which is a different runtime implementing the CRI interface. 

This article tries to explain it better:
https://medium.com/cri-o/container-runtimes-clarity-342b62172dc3

**Comment by SimonHoenscheid** [comment]
@dal00 I just want to add support for cri-o as alternative container runtime. We used it in my previous company and I added the support to the module. I am currently doing a rebase of the changes for the current version. Exspect the PR next week.

**Comment by jayunit100** [comment]
@SimonHoenscheid  can I try out your module ? this is really exciting !

**Comment by jayunit100** [comment]
I do see https://github.com/puppetlabs/puppetlabs-kubernetes/pull/265/files , but presumeably another PR on the way for the CRIO stuff? 

I was wondering if maybe there was a CRIO puppet forge recipe that could be installed standalone.

**Comment by SimonHoenscheid** [comment]
@jayunit100 sorry I was on vacation, will try to finish this up tomorrow and write the missing tests

**Comment by dal00** [comment]
Any update on this?

**Comment by SimonHoenscheid** [comment]
Yes, testing is done, I will wrap this up next week in Budapest at contributor summit.

**Comment by carabasdaniel** [comment]
Closing this issue as PR: https://github.com/puppetlabs/puppetlabs-kubernetes/pull/312/files has not been re-opened with required acceptance testing added
