### ISSUE TITLE
Kubernetes Version support and config changes

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-kubernetes#178]
The Kubernetes config is evolving, and the structure is changing (apiVersion). Therefor it would be the best to provide different templates or conditions inside the templates. Are there plans to deprecate older versions soon or will there be a limit of supported versions?

**Comment by kbarber** [comment]
In particular, this module atm won't support 1.12.2, without the ability to escape-hatch the template for `config.yaml`:

```Notice: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[njr-farm-07]/Exec[kubeadm init]/returns: your configuration file uses an old API spec: "kubeadm.k8s.io/v1alpha1". Please use kubeadm v1.11 instead and run 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
Error: 'kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors='cri'' returned 1 instead of one of [0]
Error: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[njr-farm-07]/Exec[kubeadm init]/returns: change from 'notrun' to ['0'] failed: 'kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors='cri'' returned 1 instead of one of [0]```

**Comment by kbarber** [comment]
Its a dirty hack, but might allow people to get their versioning up to 1.12.x until this module gets its overhaul: https://github.com/puppetlabs/puppetlabs-kubernetes/pull/180

**Comment by SimonHoenscheid** [comment]
@davejrt Does the module reflect the Kubernetes support lifecycle?

**Comment by davejrt** [comment]
as of PR #181 we support 1.12

@SimonHoenscheid do you have the link to that page where they outline the support lifecycle? We've not defined a definite support period but as we've previously done, we will at some point be dropping support in upcoming releases as it becomes too difficult to support that many configurations in one version of a module.
