### ISSUE TITLE
Data in Modules

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-kubernetes#179]
I played around with a feature branch at work, replacing the params.pp with module data completely. What are the plans for this from a maintainers perspective?

**Comment by davejrt** [comment]
At this stage it's not on our immedidate roadmap, but I would be happy to review a community PR that addresses this issue.

**Comment by davejrt** [comment]
Will close this, and keep the discussion going in #169 where this was initially reported.
