### ISSUE TITLE
kubernetes_version hiera key does not set kubernetesVersion in /etc/kubernetes/config.yaml

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#184]
** Is this a BUG REPORT? **
YES

## What you expected to happen?

I would expect the 'kubernetes_version' hiera key to be reflected in /etc/kubernetes/config.yaml as the kubernetesVersion parameter.

## What happened?
The config template does not support this.

## How to reproduce it?
Set kubernetes::kubernetes_version hiera value
Run puppet
Inspect /etc/kubernetes/config.yaml and kubernetesVersion is not set.

## Anything else we need to know?
This means that kubeadm init attempts to pull the wrong versions of the images.

## Versions:
puppetlabs-kubernetes 3.0.1 and master @ 3711d9f0ed2b2910df52e7aa4ec5b4b7535cb839

$ puppet --version
4.7.0
$ kubectl version
v1.11.3
$ docker version OR crictl version
17.03.0-ce
$ facter os
{
  architecture => "x86_64",
  distro => {
    codename => "n/a",
    description => "Oracle Linux Server release 7.5",
    id => "OracleServer",
    release => {
      full => "7.5",
      major => "7",
      minor => "5"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "OracleLinux",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

**Comment by davejrt** [comment]
Addressed in PR #185

**Comment by nickperry** [comment]
@davejrt your change in PR #185 doesn't work. You've put kubernetesVersion in kind: InitConfiguration, but it doesn't do anything there. It needs to be in kind: ClusterConfiguration.

**Comment by nickperry** [comment]
Thanks for the quick turn-around on PR #211
