### ISSUE TITLE
manifests/packages.pp fix archive resource with path

### ISSUE THREAD

**Issue by ladlavj** [puppetlabs/puppetlabs-kubernetes#188]
## What happened?
I'm running puppet version 5.3.3 and trying to install kubernetes controller on CentOS 7
Etcd installation fails from archive, it fails while looking for archive on path=>"/${archive}" while archive is by default downloaded under /tmp/

## How to reproduce it?
run puppet agent on centos 7

## Anything else we need to know?
seems the default behaviour of puppet resource "archive" is to download archive under /tmp and failing on line 96 of manifests/packages.pp

## Versions:

```
$ puppet --version
5.3.3

$ kubectl version

$ docker version OR crictl version

$ facter os

$ puppet module list
```

## Logs:
```
Error: Could not set 'present' on ensure: No such file or directory -  at 96:/etc/puppetlabs/code/environments/xyz/modules/kubernetes/manifests/packages.pp
Error: Could not set 'present' on ensure: No such file or directory -  at 96:/etc/puppetlabs/code/environments/xyz/modules/kubernetes/manifests/packages.pp
Wrapped exception:
No such file or directory -
Error: /Stage[main]/Kubernetes::Packages/Archive[etcd-v3.1.12-linux-amd64.tar.gz]/ensure: change from absent to present failed: Could not set 'present' on ensure: No such file or directory -  at 96:/etc/puppetlabs/code/environments/xyz/modules/kubernetes/manifests/packages.pp

```

**Comment by davejrt** [comment]
The archive type is specified with a `path` param that downloads the file to the root directory [here](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/fa21bee28a8456093bb0ae459dc930da3fccb71c/manifests/packages.pp#L103)

Line 96 in this module also referes to the containerd archive, which shouldn't be run unless you've specified containerd as the runtime.

I can't replicate the issue with a default configuration. If you need more assistance can you complete the rest of the template, and provide node definitions and hiera files that pertain to this configuration.

**Comment by davejrt** [comment]
closing due inactivity. please re open with more information if you continue to see this error
