### ISSUE TITLE
etcd requires manual intervention to update

### ISSUE THREAD

**Issue by keur** [puppetlabs/puppetlabs-kubernetes#190]
## What you expected to happen?

When bumping the version of etcd, I expect that the the binary in `/usr/local/bin/etcd` and `/usr/local/bin/etcdctl` will be updated to the specified versions, and the etcd service is restarted to reflect the latest version.

## What happened?

The version stays the same. I suspect the reason for it is due to [this line](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/fa21bee28a8456093bb0ae459dc930da3fccb71c/manifests/packages.pp#L109). If one runs `rm -f /usr/local/bin/etcd*` the files will be created.

## How to reproduce it?

First set up a simple controller and puppet the machine.

```puppet
class { 'kubernetes':
    controller    => true,
    manage_etcd   => true,
    etcd_version  => '3.0.4',
    ...
}
```

Then bump the `etcd_version` and the binary will not change on disk.

## Anything else we need to know?

Furthermore, if one does remove the files and then triggers a puppet run, the `etcd` service is not restarted. This also requires manual intervention. I'm happy to work on this issue. Just wondering if ya'll have an idea for how to go about fixing this.

**Comment by scotty-c** [comment]
We are moving etcd back to running into a container to fix this issue. That won't make the next release. It will be the one after.

**Comment by nickperry** [comment]
@scotty-c @davejrt out of interest, why do you a return to the container approach over managing etcd via a system package per https://github.com/puppetlabs/puppetlabs-kubernetes/pull/165 ?

**Comment by davejrt** [comment]
@nickperry we'll be supporting the etcd package as it currently is, as well as adding in the ability to run etcd as a container via kubeadm.

**Comment by TJM** [comment]
I think the best solution for this would be to expand etcd into /usr/local/etcd-$VERSION and create a symlink from /usr/local/bin instead of the `--strip-components` near the line that @keur mentioned above that causes the files to be extracted to /usr/local/bin directly. This would also require:

* Remove the `extract_comand` line (as this is what is stripping off the name of the folder)
* Update the `creates` to be `/usr/local/etcd-${VERSION}`
* Update the `extract_path` to `/usr/local`
* Add file (symlink) resources to link in the binaries to /usr/local/bin
* Add a notify to either the link(s) or the archive to Service['etcd'] (handles the restart when a new version is deployed)

AT least ;)

**Comment by scoopex** [comment]
Also related to #417

**Comment by scoopex** [comment]
Probably it would be also a good idea to use the checksum flags of puppet/archive.
(see https://forge.puppet.com/puppet/archive)

As i can remember puppet/archive downloads the archive again if the checksum does not match.

kubernetes::packages might have the following options with the following defaults:

* archive_checksum_type: sha256
* etcd_archive_checksum: undef
* containerd_archive_checksum: undef
* runc_checksum: undef

If a checksum is defined, it should be checked.
If the archive is downloaded and extracted, the depended services should be notified.
This provides also a improvment from a security perspective.

**Comment by scoopex** [comment]
Started to fix that at https://github.com/scoopex/puppetlabs-kubernetes/tree/component_installation for all archives/components.
From my point of view that works, but i would be very happy for feedback which helps me to find some edge cases :-)

**Comment by carabasdaniel** [comment]
Closing issue as PR#420 has been merged
