### ISSUE TITLE
apiserver_extra_arguments is ignored unless apiserver_cert_extra_sans is non-empty

### ISSUE THREAD

**Issue by dkess** [puppetlabs/puppetlabs-kubernetes#194]
## What you expected to happen?
When I fill in `apiserver_extra_arguments`, I expect the list to show up in `/etc/kubernetes/config.yaml`.
## What happened?
The extra arguments did not appear.

## How to reproduce it?
Configure puppet with `apiserver_extra_arguments` but without `apiserver_cert_extra_sans`.

## Anything else we need to know?
Looks like this is caused by an overly-aggressive if statement in the config file template.

**Comment by davejrt** [comment]
fixed in #200
