### ISSUE TITLE
New settings have not been documented

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#202]
https://github.com/puppetlabs/puppetlabs-kubernetes/pull/192

introduced new settings

$kubernetes::manage_kernel_modules
$kubernetes::manage_sysctl_settings

These need to be added to the Readme.

**Comment by davejrt** [comment]
They'll be updated before next release, we already have tickets in place to ensure the readme is up to date and the time of publishing to the forge.

It should be noted as previously stated that running from master does not reflect a production ready module.

**Comment by nickperry** [comment]
Not a problem, just highlighting these ones as I noted that previously contributors had been asked to add their own entries to the readme for new settings, before their PR was accepted. I only noticed them as I had to find and disable manage_sysctl_settings to fix a duplicate declaration in our env.

**Comment by SimonHoenscheid** [comment]
I have noticed this after merge, PR in progress
