### ISSUE TITLE
Puppet run fails if $manage_kernel_modules is set to true and $manage_sysctl_settings is set to false.

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#208]
** Is this a BUG REPORT? **
YES

## What you expected to happen?

Puppet run to complete without errors.

## What happened?
Puppet run fails with
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Invalid relationship: Kmod::Load[br_netfilter] { before => Sysctl[net.bridge.bridge-nf-call-iptables] }, because Sysctl[net.bridge.bridge-nf-call-iptables] doesn't seem to be in the catalog
```

## How to reproduce it?
Set kubernetes::manage_sysctl_settings: false in your hiera data.
Run Puppet

## Anything else we need to know?
This bug was introduced in https://github.com/puppetlabs/puppetlabs-kubernetes/pull/206 in this line
https://github.com/davejrt/puppetlabs-kubernetes/blob/7d743b4d28756d1232bc466e1e76d7431b416d13/manifests/packages.pp#L35

## Versions:
puppetlabs-kubernetes master @ 994cbd0bea55039c451443b574a7169dc4739efb

$ puppet --version
4.7.0
$ kubectl version
v1.11.3
$ docker version OR crictl version
17.03.0-ce
$ facter os
{
  architecture => "x86_64",
  distro => {
    codename => "n/a",
    description => "Oracle Linux Server release 7.5",
    id => "OracleServer",
    release => {
      full => "7.5",
      major => "7",
      minor => "5"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
  family => "RedHat",
  hardware => "x86_64",
  name => "OracleLinux",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

**Comment by davejrt** [comment]
We will address these issues when we can, due to the departure of some team members the backlog is bigger than usual. Feel free to contribute PR's as you see fit if you're running off master

**Comment by davejrt** [comment]
Out of interest are you managing one of these settings outside the module?

**Comment by nickperry** [comment]
Yes, the sysctl bit. We manage it in our base profile as part of our infosec mandated hardening.

**Comment by davejrt** [comment]
Thanks for clarifying, let me see what I can do

**Comment by davejrt** [comment]
@nickperry one would assume that you're also turning on the kernel module in your infosec hardening too? That being the case, why wouldn't you also turn off `$manage_kernel_modules` too?

**Comment by nickperry** [comment]
So by default our infosec hardening manifests ensure the sysctl resource in question is disabled, but this can be overridden for server roles like kube hosts that legitimately need it. The infosec manifests in our base profile do not attempt to ensure the presence of kernel module though.

**Comment by SimonHoenscheid** [comment]
@nickperry @davejrt that was exactly the behavior I intended, I did not exspect that people would handle one of the two. With the added relationship, this is now a problem. This problem could be fixed with a defined check for a ressource, but I would suggest you handle both parts external and deactivate both.

Suggestion: move kernel modules and sysctl configs in one condition.
