### ISSUE TITLE
Fact resolution failed

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-kubernetes#218]
## What you expected to happen?
Puppet runs smoothly

## What happened?
This issue is related to #174, which is a PR I made myself.

On Centos7/RedHat 7 the fact 

`facts['os']['distro']['codename']` 

can not be resolved and results in the following error:

` Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Operator '[]' is not applicable to an Undef Value. (file: /etc/puppetlabs/code/environments/production/modules/kubernetes/manifests/init.pp, line: 369, column: 64) on node foo.bar.baz
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

Affects the Params:

$kubernetes_apt_release and $docker_apt_release

## How to reproduce it?
run the module on centos7/redhat7

## Anything else we need to know?
I am not sure how to resolve this, for me this is a handling error inside facter/puppet.
## Versions:

puppet --version

5.5.7

kubectl version

Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

facter os

{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.5.1804",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

**Comment by davejrt** [comment]
My recommendation would just be to use the newer syntax with a legacy fact and raise a bug against facter referencing this issue.

**Comment by SimonHoenscheid** [comment]
Sounds like a good solution, exspect my PR today

**Comment by jorhett** [comment]
Install `redhat-lsb-core` which installs `lsb_release` which is what provides the fact's data source.
