### ISSUE TITLE
Please cut versions more regularly

### ISSUE THREAD

**Issue by temujin9** [puppetlabs/puppetlabs-kubernetes#238]
After the successful merge of #193, I have had to pin my local deployments to a git hash (1196f55). No currently available version includes it, and tracking master was causing failures.

Please consider cutting v3.1.1, which ties to that hash or something close to it, and then 3.1.2 (or 3.2.0, as appropriate) containing the rest of the recent updates.

**Comment by davejrt** [comment]
3.2.0 has been released. Apologies for the delays

**Comment by temujin9** [comment]
Thanks!
