### ISSUE TITLE
Allow proxy usage for kubectl

### ISSUE THREAD

**Issue by puetzp** [puppetlabs/puppetlabs-kubernetes#239]
One issue that keeps cropping up for me is the inability to pass a proxy URL to kubectl. If a node has no direct internet access kubectl is unable to download and install, for example, the CNI plugins and RBAC bindings. This case is not unusual in corporate environments.
Would it be possible to add an additional proxy parameter to the kubernetes module that is passed as environment variable to the relevant Execs (kubectl apply ...)?

Example:

```puppet
class kubernetes::kube_addons (
   ...
   Optional[String] $kubectl_proxy = $kubernetes::kubectl_proxy  # HTTPS_PROXY=https://...
) {

if $cni_rbac_binding {
    exec { 'Install calico rbac bindings':
    command => "kubectl apply -f ${cni_rbac_binding}",
    environment => "${kubectl_proxy}"
    onlyif  => 'kubectl get nodes',
    unless  => 'kubectl get clusterrole | grep calico'
    }
  }

}
```

Let me know what you think!

**Comment by davejrt** [comment]
Hi

Given we already set this here https://github.com/puppetlabs/puppetlabs-kubernetes/blob/48c77141da0040ac8e35b7fbdccd3a135f9fef16/manifests/kube_addons.pp#L14

I think the best option is just to expose that as a param, with what we currently have as the defaults, then if you need a proxy or something like that you can change them so suit your environment.

**Comment by nickperry** [comment]
I think you have two options.

1. Set the parameters on the Exec as above, but as well as setting HTTPS_PROXY, also set NO_PROXY to cover your node and any other internal addresses.

2. What we do in my organisation is to just mirror the CNI provider manifest on an internal repository and set the param cni_network_provider to reflect that. We actually install all kubernetes packages and container images (including the pause container) from local repos.

**Comment by puetzp** [comment]
Thank you for your input. I ended up doing something similar to your second option, storing the CNI manifest as a puppet template. This is fine as long as a manifest is of small size (which they usually are, fortunately). 
Since Docker provides an option for proxying I will probably continue to pull images from GCR and co.

Again, thank you for your suggestions. I'm happy with the workaround, so I don't necessarily need a proxy option anymore, but you might still want to consider it in a future version :)

Cheers!

**Comment by davejrt** [comment]
Thanks for the feedback @puetzp. I'll close this issue for now but we'll look at what options we can add in future to simplify this.
