### ISSUE TITLE
Missing kubetool container

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/puppetlabs-kubernetes#241]
The documentation describes that your should execute the following:

```
docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:{$module_version}
```

The puppet forge page lists release 3.2.0 and 3.1.0, bhut container with that release does not exist.
```
$ docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:3.2.0
Unable to find image 'puppet/kubetool:3.2.0' locally
docker: Error response from daemon: manifest for puppet/kubetool:3.2.0 not found.
See 'docker run --help'.
$ docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:3.1.0
Unable to find image 'puppet/kubetool:3.1.0' locally
docker: Error response from daemon: manifest for puppet/kubetool:3.1.0 not found.
See 'docker run --help'.
```

Also the releases section on github is empty:

https://github.com/puppetlabs/puppetlabs-kubernetes/releases

**Comment by davejrt** [comment]
Apologies, the container has been uploaded.

The releases section is not empty, you just need to expand the section at the top to show releases. As we are now using a different process they will not look exactly the same as previous.
