### ISSUE TITLE
Describe/test a best practice setup

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/puppetlabs-kubernetes#242]
This module is often potentially also used by users which a newbies in kubernetes.
To find out the steps to have a real-world setup is a time consuming task for every new user of this module.

Therefore a commodity setup which  is close to the common best practice/production grade configuration would be extremely useful.
Ideally there is a demo vagrant setup which solves this issue.

For my personal puppet developments i use my development template from https://github.com/scoopex/puppet-kitchen_template to develop and infrastructure-test (i.e. serverspec) my setups.
The setup utilizes virtualbox, vagrant and kitchen.
Probably this is a good inspiration for this task - please let me know if i can support this.

**Comment by davejrt** [comment]
@scoopex we have a repo that does this called KREAM

You can find all the information [here](https://github.com/puppetlabs/kream)
