### ISSUE TITLE
PKI keys are world-readable

### ISSUE THREAD

**Issue by dkess** [puppetlabs/puppetlabs-kubernetes#244]
Everything in the `/etc/kubernetes/pki` directory is world-readable, which means having any code execution on a Kubernetes master can lead to compromise of the cluster. Keys should have `0600` permissions.

**Comment by keur** [comment]
[Relevant code](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/48c77141da0040ac8e35b7fbdccd3a135f9fef16/manifests/config.pp#L67)

**Comment by dkess** [comment]
`/etc/kubernetes/config.yaml` also has the bootstrap token in it, so that should be root readable only as well.

**Comment by davejrt** [comment]
Closed in #248  and released with 3.2.1
