### ISSUE TITLE
Timeout error during kubeadm init step

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#256]
## What you expected to happen?
Kubernetes to be installed properly on a single master.

## What happened?
I get the error ```error marking master: timed out waiting for the condition``` during the ```kubeadm init``` step.

## How to reproduce it?
First I generated my Hiera configuration with (IP/hostname replaced):
```
docker run --rm \
           -v $(pwd):/mnt \
           -e OS=redhat \
           -e VERSION=1.10.2 \
           -e CONTAINER_RUNTIME=docker \
           -e CNI_PROVIDER=weave \
           -e ETCD_INITIAL_CLUSTER=kubernetes-master:1.2.3.4 \
           -e ETCD_IP=1.2.3.4 \
           -e KUBE_API_ADVERTISE_ADDRESS=1.2.3.4 \
           -e INSTALL_DASHBOARD=true puppet/kubetool:3.2.0
```

And I installed Kubernetes with this Puppet code:

```
  class { 'kubernetes':
    controller => true,
  }
```

## Versions:

```
$ puppet --version
5.3.5

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

$ docker version OR crictl version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:36:45 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.6",
    major => "7",
    minor => "6"
  },
  selinux => {
    enabled => false
  }
}
```

## Logs:

When I run ```systemctl status kubelet```, the process is active, but the logs show errors like ```Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady``` and ```Unable to register node "kubernetes-master.foo.com" with API server: nodes "kubernetes-master.foo.com" is forbidden```.

When i do a ```docker ps```, I see all the Kubernetes containers active as expected.

When I do a ```kubectl get pods``` I get ```The connection to the server localhost:8080 was refused - did you specify the right host or port?```

Any ideas on what might be configured wrong?

Thanks!

**Comment by SimonHoenscheid** [comment]
Puppet tries to deploy your CNI in this time weave. Did this work out?
to get kubectl working you need to export the KUBECONFIG variable. Did you do this?

**Comment by vrmerlin** [comment]
I'm just showing the errors I got during the puppet deployment. After the "time out waiting" error, it said this:

```
Error: 'kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors=''' returned 1 instead of one of [0]
Error: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[kubernetes-master]/Exec[kubeadm init]/returns: change from 'notrun' to ['0'] failed: 'kubeadm init --config '/etc/kubernetes/config.yaml' --ignore-preflight-errors=''' returned 1 instead of one of [0]
```


Doesn't the KUBECONFIG variable come at the end of the init? It never got to that point.

**Comment by vrmerlin** [comment]
So, good news...

I changed ```VERSION=1.10.2``` (which is in your documentation) to be ```VERSION=1.13.0``` (the latest version), and then added ```etcd_version => "3.2.18"``` to my Puppet Kubernetes module constructor, and suddenly it worked! The whole thing installed successfully.

**Comment by davejrt** [comment]
Without more info I can't determine why your install with 1.10 wasn't working, but we acceptance test against this version so I dare says it's environment specific.

Having said, you alluded to the fact our documentation references 1.10...do you find this misleading?

**Comment by vrmerlin** [comment]
I tried it again, and yes, the change in versions it what seems to make it work. Could be environment specific, but no idea exactly what is different.

I'm not sure "misleading" is the word, but I assumed if "1.10" was there that it was a "safe" version to use (and it apparently is for most people). In any case, I guess i'm good to go now, and we can close this.
