### ISSUE TITLE
Use controller as a worker?

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#258]
I'm using the latest version of puppetlabs-kubernetes, and I believe I've successfully used it to set up a master and two nodes. However, I'd really like to run pods on the master as well as on the nodes. I see the sentence in the documentation, "Note:: A node cannot be a controller and a worker. It must be one or the other." But, why not? I know it's possible if I install kubernetes manually. Is there some workaround to this limitation?

**Comment by SimonHoenscheid** [comment]
By default, controller/master nodes are tainted. That is something that kubernetes does, to ensure the master has enough resources to do what is his job. So basically every node in K8s is configured the same, but masters only allow special containers to run. 
You can remove the taint, if you want to. 
https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

**Comment by vrmerlin** [comment]
Thanks for responding.

Ok, I can go that route, but I was hoping I would be able to it the “puppet” way, rather than manually on a command line after Puppet brings up a master node.

John

**Comment by SimonHoenscheid** [comment]
That is not possible. The taint is there and will not go away until you remove it. You could do this in puppet, using an exec after the master was privisioned.

**Comment by davejrt** [comment]
Set the param `schedule_on_contoller` [here](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/2827eeb6f7765bcaac981b39942a1bd79c939712/manifests/init.pp#L211) to true in your hiera and you'll be able to run pods on the master. 

It will execute [this](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/2827eeb6f7765bcaac981b39942a1bd79c939712/manifests/kube_addons.pp#L39) exec.

We use this by default in kream [here](https://github.com/puppetlabs/kream/blob/d8d53668a8265a8615ddd68312cca6c2d8e5d2d5/hieradata/Debian.yaml#L17)

**Comment by vrmerlin** [comment]
ok, thanks all. I'll use these workarounds.
