### ISSUE TITLE
This module should manage the `front-proxy-ca`

### ISSUE THREAD

**Issue by mrwulf** [puppetlabs/puppetlabs-kubernetes#275]
# BUG REPORT

## What you expected to happen?
After installing a cluster with multiple master nodes, installing `metrics-server` should just work.

## What happened?
`kubectl top nodes` would sporadically work. After some experimentation I found that requests to one master consistently worked, and all others consistently failed. Test with `kubectl top nodes --server https://master01:6443`

## How to reproduce it?
1. Install kubernetes 1.12.5 with multiple masters
1. Install the `metrics-server`: `helm install metrics-server stable/metrics-server --version 2.6.0 --set 'args={"--kubelet-preferred-address-types=InternalIP","--kubelet-insecure-tls=true"}'`
1. Try accessing node metrics through each master: `kubectl top nodes --server https://masterX:6443`

## Anything else we need to know?
Because `metrics-server` is implemented as an aggregated api extension, the apiserver forwards requests to `metrics-server` using the front-proxy-* certificates. These certificates should all be created using the same CA.
Here are some docs: https://kubernetes.io/docs/tasks/access-kubernetes-api/configure-aggregation-layer/

## Solution
This module should manage `front-proxy-ca.crt` and `front-proxy-ca.key` and they should be deployed to the controllers before running `kubeadm init` -- just like `/etc/kubernetes/pki/ca.crt`.

Based on https://kubernetes.io/docs/setup/independent/high-availability/
Here is a related issue: https://github.com/kubernetes-incubator/metrics-server/issues/58

**Comment by nickperry** [comment]
Yeah, we've been hit by this too. I wish I'd found your bug report before I spent so many hours figuring it out for myself.

I will submit a PR in the next couple of days to fix this.

**Comment by nickperry** [comment]
Fixed in #321
