### ISSUE TITLE
no parameter named 'value'

### ISSUE THREAD

**Issue by KrisBuytaert** [puppetlabs/puppetlabs-kubernetes#284]
We've been running into   when 

Error 500 on SERVER: Server Error: no parameter named 'value' (file: /etc/puppetlabs/code/environments/mgmtplay/modules/upstream/kubernetes/manifests/packages.pp, line: 39) on Sysctl[net.bridge.bridge-nf-call-iptables] (file: /etc/puppetlabs/code/environments/mgmtplay/modules/upstream/kubernetes/manifests/packages.pp, line: 39) on node kubemaster.mgmtplay.inuits.eu

This with 
kubernetes::manage_sysctl_settings: true

And the 

{
  "name": "herculesteam-augeasproviders_sysctl",
  "version": "2.3.1",
  "author": "Dominic Cleal, Raphael Pinson, Trevor Vaughan",
}

installed .

## Versions:

puppet --version 
5.5.10

module version 
 "name": "puppetlabs-kubernetes",
  "version": "4.0.0",

CentOS 7.6

**Comment by KrisBuytaert** [comment]
I tried  puppet generate types --environment  $environment .. but even after that it keeps giving the same error.

**Comment by daianamezdrea** [comment]
Hi @KrisBuytaert, can you please try with the latest kubernetes version and see if the problem is still there? Thank you for adressing this, I'm waiting for your response

**Comment by aleita** [comment]
Hi, same problem here with the last module version

**Comment by johnwarburton** [comment]
In case anyone else lands here - I got this error message due to a locally created <sysctl> definition 😞 

Deleted it and carried on...
