### ISSUE TITLE
No kubetool container for v4.0.1

### ISSUE THREAD

**Issue by martezr** [puppetlabs/puppetlabs-kubernetes#319]
##  What you expected to happen?
When attempting to use the kubetool docker container for the v4.0.1 version of the module I expected the image to download and run the container to generate a configuration.

## What happened?
The Docker image was not able to be found and threw the following error message. There is no new tag for the latest version of the puppet module (https://hub.docker.com/r/puppet/kubetool/tags).

manifest for docker.io/puppet/kubetool:4.0.1 not found

## How to reproduce it?
Attempt to pull the corresponding docker image from Docker hub.

docker pull puppet/kubetool:4.0.1

**Comment by daveoy** [comment]
i did manage to build the container with `docker build -t "puppet/kubetool:4.0.1" .` inside the 'tooling' directory of the module.

that may not be the solution here, as im noticing the container is making OS.yaml but not hostname.yaml. YMMV

**Comment by martezr** [comment]
@daveoy The 4.0.0 version of the container worked for me but I just wanted to highlight that the documentation states to use the tag that matches the module version but that the corresponding tag doesn't exist. Ultimately the solution will be to push the corresponding tagged version of the image to Docker hub.

**Comment by daveoy** [comment]
I tried this as well today and it also worked to generate the config.
