### ISSUE TITLE
Config etcd_ca_key appears unused and confusing

### ISSUE THREAD

**Issue by stephencroberts** [puppetlabs/puppetlabs-kubernetes#333]
Comparing the docs between [etcd](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md#basic-setup) and [this puppet module](https://forge.puppet.com/puppetlabs/kubernetes#etcd_ca_key), it appears that `etcd_ca_key` is actually unused and caused some confusion for me. I do see that the config option will create a file `ca.key` but that file does not appear to be used. Can anyone confirm and maybe update the documentation?

**Comment by TJM** [comment]
It is brought into the `kubernetes::config::kubeadm`  class: https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/manifests/config/kubeadm.pp#L9

... which creates various cert/key files: https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/manifests/config/kubeadm.pp#L58-L75

... from templates like this one: https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/templates/etcd/ca.key.erb

Of course, it would have been easier to track if it was just something like `content => $etcd_ca_key`, but they made it fancy ;)

**Comment by stephencroberts** [comment]
Thanks for taking a look @TJM. It's true, puppet does create the file, but the file isn't actually used by etcd or kubernetes from what I can tell.

> https://github.com/puppetlabs/puppetlabs-kubernetes/blob/d6a9e670b8613ab9241a4d22799290b456bfed81/templates/etcd/etcd.service.erb

**Comment by TJM** [comment]
Yea, sorry, I answered the wrong question :)
