### ISSUE TITLE
Wrong default for kubernetes::kubernetes_apt_location

### ISSUE THREAD

**Issue by aptituz** [puppetlabs/puppetlabs-kubernetes#334]
## Describe the Bug
I tried to use this module to setup kubernetes in a vagrant environment and it failed to install the kubernetes packages, since the repository location is wrong.

As the documentation states `kubernetes::kubernetes_apt_location` points to `https://apt.kubernetes.io` but in fact it points to`https://apt.kubernetes.io`.

## Expected Behavior
I would expect the module to use the default documentation as documented in the Kubernetes documentation, which is:

https://apt.kubernetes.io

**Comment by sheenaajay** [comment]
https://github.com/puppetlabs/puppetlabs-kubernetes/pull/337
Above PR contains the fix. Thank you.
