### ISSUE TITLE
Wrong default for kubernetes::kubernetes_apt_release

### ISSUE THREAD

**Issue by aptituz** [puppetlabs/puppetlabs-kubernetes#335]
## Describe the Bug
A usage of this module on Ubuntu bionic fails, because the module incorrectly assumes the kubernetes repositories to follow the notion of repository including the distribution codename.

## Expected Behavior
The module should not use $::codename for the default of `kubernetes::kubernetes_apt_release` since the kubernetes developers do not supply a codename-specific release.

Instead the module should default to "kubernetes-xenial" as this is used for all kubernetes-supported operating systems.

## Additional Context

I know that Bionic is currently not officially supported by the module, but it has to be noted that the assumption on which the module is based is wrong anyway. It's also worth to note that changing this _could_ probably also fix the compatibility with Debian.

**Comment by sheenaajay** [comment]
https://github.com/puppetlabs/puppetlabs-kubernetes/pull/338/files
