### ISSUE TITLE
Module doesn't work with newer kubernetes versions

### ISSUE THREAD

**Issue by aptituz** [puppetlabs/puppetlabs-kubernetes#336]
## Describe the Bug
Even though the documentation states that the module can be used to install kubernetes "Kubernetes 1.10.x or higher" the installation of kubernetes fails on recent versions, because the generated Kubeadm config is using the wrong API version.

This is probably because of the quiet naive version selector in https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/manifests/config/kubeadm.pp#L142

From there we can tell that for v1.12 a different api version is used, but newer versions fall into the default case.

## Expected Behavior
I would expect the module to work as documented (e.g. being able to install versions newer then 1.10.x).

To achieve that it would probably make sense to use `versioncmp` instead of a static version selector and make use of the newer api version for every version which is greater or equal 1.12.

Otherwise I'd at least expect to fail out on unsupported versions.

**Comment by flostru** [comment]
True for kubeadm upgrade to 1.15
Upgrade to 1.14 works fine since 1.14 still uses v1beta1
Reading v1beta1 wil still work in 1.15 thou but doing a manual kubeadm upgrade will migrate to v1beta2 wich will be overwritten by Puppet.
Note that an upgrade to 1.15 will rotate your certs aswell if you dont explicitely prevent that during kubeadm upgrade resulting in a broken cluster since Puppet will push your „old“ certs again.

https://godoc.org/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta2

**Comment by aptituz** [comment]
Ah, sorry, it seems I confused the api versions and was a bit to fast with my conclusion what's the problem. I'm currently doing another run to properly update my issue.

**Comment by flostru** [comment]
> Ah, sorry, it seems I confused the api versions and was a bit to fast with my conclusion what's the problem. I'm currently doing another run to properly update my issue.

No problem, you got a valid point here, even thou you might be able to spawn a new cluster with this module you might run into serious trouble when upgrading kubernetes to 1.15

**Comment by aptituz** [comment]
Okay, turns out I had a totally different issue (I specified a non semver version for kubernetes version and this caused kubeadm init to fail - the parameter could need a validation I guess :)) and draw wrong conclusions.

Nevertheless as you already pointed out, it's probably still not possible to install v1.15 (didn't test it again, though).

Whatever the solution for that I'd suggest to change the version to reflect the latest tested version instead of writing "1.10.x or higher" in the docs as I'd assume it's quiet likely to break with newer kubernetes versions anyway.

**Comment by nickperry** [comment]
We have installed 1.15.6 clusters using the module and upgraded 1.14 clusters to 1.15 without any problem. As an aside @flostru, the automatic rotation of the certs during upgrade should cause any problems - they're still signed by the original CA.

In my opinion this issue should be closed.
