### ISSUE TITLE
Put packages on hold after installation?

### ISSUE THREAD

**Issue by aptituz** [puppetlabs/puppetlabs-kubernetes#341]
## Use Case
The documentation suggests to put the kubelet, kubeadm, kubectl packages et cetera on hold after installation, which absolutely makes sense so that the admin of a kubernetes cluster can have a controlled upgrade path for the kubernetes components which is independent from the operating system upgrades.

## Describe the Solution You Would Like

In order to avoid accidental upgrades to the kubernetes components, the module should support (and in my opinion) by default set packages it installed on hold.

## Describe Alternatives You've Considered
Obviously this hold can be configured in a profile, but given that it come by surprise to the user of the module that it indeed does not set the package on hold (even though that's recommended practice as per kubernetes docs) I think having it in the module and being the default makes more sense.

## Additional Context
This section outlines the installation process according to the kubernetes project:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

I assume the process is as is because of the version skew policy - without a hold it's pretty easy to accidentally upgrade machines to a potentially dangerous state.

**Comment by scoopex** [comment]
New pull request: https://github.com/puppetlabs/puppetlabs-kubernetes/pull/416

**Comment by scoopex** [comment]
From my point of view this works now for debian based distributions

**Comment by carabasdaniel** [comment]
Closing this issue as PR with changes has already been merged
