### ISSUE TITLE
Generating the module configuration - not working

### ISSUE THREAD

**Issue by chrber** [puppetlabs/puppetlabs-kubernetes#343]
## Describe the Bug
using https://forge.puppet.com/puppetlabs/kubernetes/readme

sudo docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:5.0.0
/etc/k8s/kube_tool/other_params.rb:9:in `create': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
        from /etc/k8s/kube_tool.rb:67:in `build_hiera'
        from /etc/k8s/kube_tool.rb:82:in `<main>'

## Expected Behavior
docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:{$module_version} should exit with $? = 0

## Steps to Reproduce
1. Download https://forge.puppet.com/v3/files/puppetlabs-kubernetes-5.0.0.tar.gz
2. goto dir~/puppetlabs-kubernetes-5.0.0
3. run docker run --rm -v $(pwd):/mnt --env-file env puppet/kubetool:{$module_version}
4. regret to have executed the command:
/etc/k8s/kube_tool/other_params.rb:9:in `create': undefined method `match' for nil:NilClass (NoMethodError)
Did you mean?  catch
        from /etc/k8s/kube_tool.rb:67:in `build_hiera'
        from /etc/k8s/kube_tool.rb:82:in `<main>'

## Environment
 - Platform Ubuntu 18.04 
puppetlabs-kubernetes (v5.0.0)
  ├── camptocamp-kmod (v2.3.1)
  ├─┬ herculesteam-augeasproviders_sysctl (v2.3.1)
  │ └── herculesteam-augeasproviders_core (v2.5.0)
  ├── puppet-archive (v3.2.1)
  ├─┬ puppetlabs-apt (v6.3.0)
  │ └── puppetlabs-translate (v1.2.0)
  └── puppetlabs-stdlib (v5.2.0)
 - puppet --version 6.9.0
 - Docker version 18.09.7, build 2d0083d
 - 

## Additional Context
Puppet master and agent are on the same host

**Comment by carabasdaniel** [comment]
Hello @chrber, could you try running the command as follows, maybe one of the environment variables required was missing from the configuration: 
`docker run --rm -v $(pwd):/mnt -e OS=redhat -e VERSION=1.13.5 -e CONTAINER_RUNTIME=docker -e CNI_PROVIDER=weave -e ETCD_INITIAL_CLUSTER=kube-master:172.20.20.10 -e ETCD_IP="%{::ipaddress_eth1}" -e KUBE_API_ADVERTISE_ADDRESS="%{::ipaddress_eth1}" -e INSTALL_DASHBOARD=true puppet/kubetool:5.0.0`
