### ISSUE TITLE
It is not possible to upgrade from 5.0.0 or earlier due to Docker cgroup setting clash

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#367]
## Describe the Bug

Commit https://github.com/puppetlabs/puppetlabs-kubernetes/commit/6ad08c03ae6a7aafcda2b30c0d743246358ed72a changed where the cgroup driver for docker was set from the systemd unit file to /etc/docker/daemon.json.

After upgrading the version of the kubernetes module, you end up with the setting in both locations. These clash and the Docker service will not start.

## Expected Behavior
Should be able to upgrade from older version of the module without breaking Docker.

## Steps to Reproduce
Install Kubernetes using version 4.0.1 or earlier of the module.
Change to master at 6ad08c03ae6a7aafcda2b30c0d743246358ed72a or later.
Re-run puppet.
Reboot.
Docker will not start.

## Environment
 - 6ad08c03ae6a7aafcda2b30c0d743246358ed72a
 - RHEL 7

**Comment by catsem** [comment]
This seems to affect fresh installations too.
At least in my setup with docker-ce 19.03.6 and kubernetes 1.17.3.

My workaround for now is to add this line to the %{osfamily}.yaml

> kubernetes::cgroup_driver: "systemd"

**Comment by sazzle2611** [comment]
We have several clusters initially installed with 5.0.0 and have come across this problem. OS Centos 7.

To fix I had to manually edit the file /usr/lib/systemd/system/docker.service and change the line

ExecStart=/usr/bin/dockerd --exec-opt native.cgroupdriver=systemd

to 

ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock

And then restart docker and kubelet
