### ISSUE TITLE
Test cluster is failing

### ISSUE THREAD

**Issue by jcwarp** [puppetlabs/puppetlabs-kubernetes#37]
I'm not sure what to put in for fqdn, so I put in the bootstrap controller's fqdn
Bringing the system up, it fails with:
Notice: /Stage[main]/Kubernetes::Service/Exec[Checking for the Kubernets cluster to be ready]/returns: The connection to the server bootstrap-controller.local:6443 was refused - did you specify the right host or port?
Is there a prerequisite for the Kubernetes controllers and workers that I am missing?

**Comment by scotty-c** [comment]
@jcwarp This looks like not all the Kubernetes services have started is there any containers in crash loop ?

**Comment by scotty-c** [comment]
@jcwarp Is this still an open issue?

**Comment by jcwarp** [comment]
@scotty-c Yes, I still have the issue; sorry about the delay - a lot piled up over the holiday break.
What I see is that etcd-amd64 and kube-apiserver-amd64 are both exiting over and over.
I will look into journald and see if I can glean more info.

**Comment by scotty-c** [comment]
@jcwarp no worries, if you find anything in the logs and want to share them on this issue. more than happy to have a look and help out.

**Comment by jcwarp** [comment]
Hi Scotty... This is what I have found so far. The two containers that are failing are the etcd and kube-apiserver. I suspect it is the name resolution of the etcd container that is causing the problem.

docker logs k8s_etcd_etcd-sha-k8s-host-cass-test-1
 - [snip] etcdmain: couldn't find local name "etcd-sha-k8s-host-cass-test-1" in the initial cluster configuration

docker logs k8s_kube-apiserver_kube-apiserver-sha-k8s-host-cass-test-1
 - I0112 20:21:15.773773       1 server.go:112] Version: v1.7.3
error waiting for etcd connection: timed out waiting for the condition

I will continue investigating, but if you have any insights, they would be welcome.
Thanks!

**Comment by scotty-c** [comment]
@jcwarp can you send the hiera values you have for `kubernetes::etcd_initial_cluster:` and also the hostname of the box

**Comment by nicknezis** [comment]
@jcwarp I had a similar issue setting up a k8s cluster using kubeadm. Ended up having to run `setenforce 0` to fix the etcd failing issue. Sorry might not be related, but thought I'd mention it.

**Comment by scotty-c** [comment]
@nicknezis That is a good point, we do set that if you use Kream with RHEL

**Comment by scotty-c** [comment]
@nicknezis Is this still an open issue for you?
