### ISSUE TITLE
Renew cert process after expiration

### ISSUE THREAD

**Issue by yotles** [puppetlabs/puppetlabs-kubernetes#373]
What the correct way for cluster deployed by this module to renew certificates after their expiration after year? Did anyone faced with this procedure?

**Comment by carabasdaniel** [comment]
Hello @yotles 

Updating the certificates in the Hiera data should automatically update the files on the disk whenever a Puppet run is triggered, but a restart will be needed for the Kubernetes component to pick up the new configuration on those machines. 

If you update the certificates through kubeadm cli, these will be rewritten in the configuration files from the hiera data.

**Comment by abegosum** [comment]
What is the recommended way of updating the certificates in hiera?  Just a re-run of the kubetool container?

**Comment by TheMeier** [comment]
This issue ist still relevant.
