### ISSUE TITLE
Failed Installation on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by bitvijays** [puppetlabs/puppetlabs-kubernetes#381]
## Describe the Bug
Trying to install kubernetes using puppetlabs-kubernetes on Ubuntu 18.04.3 LTS using Puppet.

## Expected Behavior
Kubernetes getting installed.

## Steps to Reproduce

1. Try to install Kubernetes using Puppet. Below is the site.pp manifest file

Site.pp 

```
class profile::kubernetes_server{
        class {'kubernetes':
           controller => true,
        }
}
```
node 'example.local'{
        include profile::kubernetes_server                                                                                                                                                                                                   }

2. Run `Puppet agent -t` on example.local

## Environment
 - Version [e.g. 1.27.0]
 - Platform: Ubuntu 18.04.3

## Additional Context
Error Encountered.
```
Error: Could not set 'present' on ensure: The id in your manifest D0BC747FD8CAF7117500D6FA3746C208A7317B0F and the fingerprint from content/source don't match. Check for an error in the id and content/source is legitimate. (file: /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp, line: 55)
Error: Could not set 'present' on ensure: The id in your manifest D0BC747FD8CAF7117500D6FA3746C208A7317B0F and the fingerprint from content/source don't match. Check for an error in the id and content/source is legitimate. (file: /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp, line: 55)
Wrapped exception:
The id in your manifest D0BC747FD8CAF7117500D6FA3746C208A7317B0F and the fingerprint from content/source don't match. Check for an error in the id and content/source is legitimate.
Error: /Stage[main]/Kubernetes::Repos/Apt::Source[kubernetes]/Apt::Key[Add key: D0BC747FD8CAF7117500D6FA3746C208A7317B0F from Apt::Source kubernetes]/Apt_key[Add key: D0BC747FD8CAF7117500D6FA3746C208A7317B0F from Apt::Source kubernetes]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: The id in your manifest D0BC747FD8CAF7117500D6FA3746C208A7317B0F and the fingerprint from content/source don't match. Check for an error in the id and content/source is legitimate. (file: /etc/puppetlabs/code/environments/production/modules/apt/manifests/key.pp, line: 55)
```

**Comment by carabasdaniel** [comment]
Hi @bitvijays 

Currently the kubernetes_apt_location parameter defaults to https://apt.kubernetes.io and as you can see from the error message this is an apt error. There are different workaround if you want to install Kubernetes on Ubuntu Bionic but, for now, this module is compatible with Ubuntu Xenial as shown in the metadata.json of this module.

**Comment by bitvijays** [comment]
@carabasdaniel Hope you re doing well. Thank you for your response. My apologies, would it be possible for you to tell me a simplest workaround? Is there a way we can change the kubernetes_apt_location of any other variable to get Kubernetes installed?

**Comment by catsem** [comment]
I had the same issue.
With the following config I could setup the cluster in ubuntu bionic:

> kubernetes::kubernetes_version: 1.17.3
kubernetes::docker_apt_location: "https://download.docker.com/linux/ubuntu"
kubernetes::docker_apt_release: "bionic"
kubernetes::docker_apt_repos: "stable"
kubernetes::docker_key_source: "https://download.docker.com/linux/ubuntu/gpg"
kubernetes::docker_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
kubernetes::docker_version: "5:19.03.6~3-0~ubuntu-bionic"
kubernetes::docker_package_name: "docker-ce"
kubernetes::cgroup_driver: "systemd"

IMHO kubernetes and this module should finally start to support ubuntu 18.04 as the current LTS. It's already on the market for about 2 years now and even worse, 16.04 is hitting it's end of standard support next year.

**Comment by bitvijays** [comment]
@carabasdaniel Hope you are doing well. Would it be possible to add @catsem suggestion in the Readme.md? May be in a subsection. 

**Just a example below**

## Installing a updated version

If you want to install a updated version/ customise the installation, please change the below parameters:
```
kubernetes::kubernetes_version: 1.17.3
kubernetes::docker_apt_location: "https://download.docker.com/linux/ubuntu"
kubernetes::docker_apt_release: "bionic"
kubernetes::docker_apt_repos: "stable"
kubernetes::docker_key_source: "https://download.docker.com/linux/ubuntu/gpg"
kubernetes::docker_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
kubernetes::docker_version: "5:19.03.63-0ubuntu-bionic"
kubernetes::docker_package_name: "docker-ce"
kubernetes::cgroup_driver: "systemd"
```

@catsem Would it be possible for you to send a PR for the Readme.md? If @carabasdaniel is fine with the suggestion?
