### ISSUE TITLE
Flannel hard-coded to use 10.244.0.0/16

### ISSUE THREAD

**Issue by jonjhallettuob** [puppetlabs/puppetlabs-kubernetes#397]
## Describe the Bug
Setting the CNI provider to Flannel causes CNI to ignore the `kubernetes::cni_pod_cidr` Hiera parameter, and always uses 10.244.0.0/16 as the CNI pod CIDR for the `cni0` interface.

For example, setting `kubernetes::cni_pod_cidr: 10.0.0.0/16` results in the `flannel.1` interfaces using an address from 10.0.0.0/16, but the `cni0` interface will incorrectly be allocated from `10.244.0.0/16`.

The pod CIDR appears to be hard-coded in `net-conf.json` config embedded in the YAML file specified at https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/tooling/kube_tool/other_params.rb#L26

## Expected Behavior
The `cni0` interface should use an address from the range specified by `kubernetes::cni_pod_cidr`.

## Steps to Reproduce
Attempt to install a Kubernetes worker with

```
  class { 'kubernetes':
    worker => true,
  }
```

The Hiera configuration is of the form below.

```
kubernetes::kubernetes_version: 1.15.7
kubernetes::kubernetes_package_version: 1.15.7
kubernetes::container_runtime: docker
kubernetes::cni_network_provider: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
kubernetes::cni_pod_cidr: 10.0.0.0/16
kubernetes::etcd_initial_cluster:[...],[..],[...]
kubernetes::etcd_peers:
- [...]
- [...]
- [...]
kubernetes::etcd_ip: "%{::ipaddress_eth0}"
kubernetes::kube_api_advertise_address: "%{::ipaddress_eth0}"
kubernetes::api_server_count: 3
kubernetes::install_dashboard: true
kubernetes::controller_address: [...]
```
This will result in an interface called `cni0` using an address in 10.244.0.0/16.

## Environment
```
# puppet --version
5.5.10

# facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.7.1908",
    major => "7",
    minor => "7"
  },
  selinux => {
    config_mode => "enforcing",
    current_mode => "enforcing",
    enabled => true,
    enforced => true,
    policy_version => "31"
  }
}
$ grep kubernetes Puppetfile
  mod 'puppetlabs-kubernetes', '5.0.0'
```

## Additional Context
At our site, policy dictates that all machine-local traffic uses 10.0.0.0/16. Potentially 10.244.0.0/16 is used for onsite routed services, and having an interface on 10.244.0.0/16 causes routing problems.

**Comment by chelnak** [comment]
Hello! This limitation is actually set by flannel.

https://github.com/flannel-io/flannel/blob/74b5e5061db72edb2e6911e11e60ff5bd0871d63/Documentation/kube-flannel.yml#L128

Because we directly consume this manifest there is no (sensible) way to change this. 

Therefore alternate configurations are not supported at this time.

Thank you!
