### ISSUE TITLE
Improve documentation for litmus acceptance tests

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/puppetlabs-kubernetes#399]
Section https://github.com/puppetlabs/puppetlabs-kubernetes#development describes how to run the litmus tests.

I never used litmus before and i ran in the following problem:
```
$ bundle exec rake 'litmus:provision_list[all_supported]'
rake aborted!
Don't know how to build task 'litmus:provision_list' (See the list of available tasks with `rake --tasks`)
/home/schoecmc/.rvm/gems/ruby-2.4.1/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/schoecmc/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/schoecmc/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```
It would be great to have a complete description how to use litmus.

**Comment by carabasdaniel** [comment]
Hi @scoopex 
In order to run the acceptance tests with Litmus you need to use Ruby > 2.5.

For more information about Litmus please see [the wiki](https://github.com/puppetlabs/puppet_litmus/wiki).

**Comment by scoopex** [comment]
It fails withe following step:
```
$ bundle exec rake 'litmus:install_module'
Built
127.0.0.1:2200 failed {"stdout"=>"", "stderr"=>"sh: 1: puppet: not found\n", "exit_code"=>127, "_error"=>{"kind"=>"puppetlabs.tasks/command-error", "issue_code"=>"COMMAND_ERROR", "msg"=>"The command failed with exit code 127", "details"=>{"exit_code"=>127}}}
127.0.0.1:2201 failed {"stdout"=>"", "stderr"=>"sh: 1: puppet: not found\n", "exit_code"=>127, "_error"=>{"kind"=>"puppetlabs.tasks/command-error", "issue_code"=>"COMMAND_ERROR", "msg"=>"The command failed with exit code 127", "details"=>{"exit_code"=>127}}}
Installed
```

Is that originated in the "puppet module install " commands in spec/spec_helper_acceptance_local.rb ?

**Comment by carabasdaniel** [comment]
Closed issue as PR: https://github.com/puppetlabs/puppetlabs-kubernetes/pull/401 was merged. 

The issue you had with the install module rake task failure is happening because the puppet agent is not installed on those machines (127.0.0.1:2200 and 127.0.0.1:2201). The install_module rake task builds the module you are working on and installs it on the test machine from the tarball.
