### ISSUE TITLE
Module is using old repo - disabled yesterday

### ISSUE THREAD

**Issue by RealGrimbi** [puppetlabs/puppetlabs-kubernetes#402]
## Describe the Bug
https://yum.dockerproject.org/repo/main/centos/7/repodata/repomd.xml
If Repo is updated manually from Link below:
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install docker-engine-17.03.1.ce-1.el7.centos' returned 1: Error: Nothing to do
Error: /Stage[main]/Kubernetes::Packages/Package[docker-engine]/ensure: change from 'purged' to '17.03.1.ce-1.el7.centos' failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install docker-engine-17.03.1.ce-1.el7.centos' returned 1: Error: Nothing to do
Notice: /Stage[main]/Kubernetes::Packages/File[/etc/docker/daemon.json]: Dependency Package[docker-engine] has failures: true
Warning: /Stage[main]/Kubernetes::Packages/File[/etc/docker/daemon.json]: Skipping because of failed dependencies
Warning: /Stage[main]/Kubernetes::Packages/File[/etc/systemd/system/docker.service.d]: Skipping because of failed dependencies
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install kubelet-1.19.0' returned 1: Error: Nothing to do
Error: /Stage[main]/Kubernetes::Packages/Package[kubelet]/ensure: change from 'purged' to '1.19.0' failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install kubelet-1.19.0' returned 1: Error: Nothing to do
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install kubectl-1.19.0' returned 1: Error: Nothing to do
Error: /Stage[main]/Kubernetes::Packages/Package[kubectl]/ensure: change from 'purged' to '1.19.0' failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install kubectl-1.19.0' returned 1: Error: Nothing to do
Error: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install kubeadm-1.19.0' returned 1: Error: Nothing to do
Error: /Stage[main]/Kubernetes::Packages/Package[kubeadm]/ensure: change from 'purged' to '1.19.0' failed: Could not update: Execution of '/usr/bin/yum -d 0 -e 0 -y install kubeadm-1.19.0' returned 1: Error: Nothing to do

## Expected Behavior
Module should use the correct repo:
https://docs.docker.com/install/linux/docker-ce/centos/

## Steps to Reproduce
Clean install of OS

## Environment
CentOS 7

## Additional Context
Docker cannot be installed

**Comment by dverdonschot** [comment]
We face the same issue. The yum repo is not working, and docker-engine deprecated by docker-ce.

**Comment by binford2k** [comment]
resolved in #414
