### ISSUE TITLE
Invalid field in v1beta1 kubeadm config template

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#406]
## Describe the Bug
`error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "max"`

## Expected Behavior
kubeadm init should run cleanly

## Steps to Reproduce
Apply module on control plane nodes, when the module runs kubeadm init, you will see the error `error unmarshaling configuration schema.GroupVersionKind{Group:"kubeproxy.config.k8s.io", Version:"v1alpha1", Kind:"KubeProxyConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "max"`.

## Environment
4.0.0 - 5.1.0 and still present on master, but fixed in v1beta2 template.
RHEL7

## Additional Context
This is because this field is not valid. See https://github.com/kubernetes/kube-proxy/blob/master/config/v1alpha1/types.go#L70-L84. Min is a valid field but Max is not.

This is the offending line in the template:

https://git.nonprod.williamhill.plc/external/puppetlabs-puppetlabs-kubernetes/-/blob/master/templates/v1beta1/config_kubeadm.yaml.erb#L112

**Comment by sheenaajay** [comment]
PR is merged. Thank you @nickperry for your contribution.
