### ISSUE TITLE
Automatic restart of etcd

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/puppetlabs-kubernetes#417]
Changes of /etc/systemd/system/etcd.service do not trigger a restart of etcd.

I upgraded puppetlabs-kubernetes and goth the following changes.

```
Notice: /Stage[main]/Kubernetes::Config::Kubeadm/File[/etc/systemd/system/etcd.service]/content: 
--- /etc/systemd/system/etcd.service	2020-03-27 09:54:32.859358311 +0100
+++ /tmp/puppet-file20200608-208370-1v3f8d9	2020-06-08 11:26:12.155423815 +0200
@@ -27,7 +27,11 @@
     --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt \
     --initial-cluster k8s-c1t-con-001=https://10.23.22.121:2380,k8s-c1t-con-002=https://10.23.22.122:2380,k8s-c1t-con-003=https://10.23.22.123:2380 \
     --initial-cluster-token my-etcd-token \
-    --initial-cluster-state new
+    --initial-cluster-state new \
+    --auto-compaction-retention 0 \
+    --auto-compaction-mode periodic \
+    --max-wals 5
+
```

## Expected Behavior

ETCD ist not automatically restarted after systemd was configured.
From my point of view it should be configurable that etcd is restarted on upgrades of reconfiguration.
(automatic_restart_etcd: true|false)
On change of the system unit file, a "systemctl daemon-reload" should also be executed.

**Comment by scoopex** [comment]
Still relevant :-)

**Comment by deric** [comment]
@scoopex Which version of `puppetlabs-kubernetes` do you use? [Following lines](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/main/manifests/service.pp#L80):
```puppet
  File <|
    path == '/etc/systemd/system/kubelet.service.d' or
    path == '/etc/default/etcd' or
    path == '/etc/systemd/system/etcd.service'
    |> ~> Service['etcd']
```
should trigger `etcd` restart. The change was [introduced in 6.0.0](https://github.com/puppetlabs/puppetlabs-kubernetes/commit/6f7faf6b3adb91d87ed23d26d7d6e16a7fe1fd8f).
