### ISSUE TITLE
Acceptance tests not usable for unexperienced litmus users

### ISSUE THREAD

**Issue by scoopex** [puppetlabs/puppetlabs-kubernetes#419]
## Describe the Bug

The described steps in section "Development" are not working on Ubuntu 18.04.

See details in 
[litmus.txt](https://github.com/puppetlabs/puppetlabs-kubernetes/files/4774295/litmus.txt)

## Expected Behavior

The procedure to setup and user litmus tests is described in a complete way.
The user doesn't need extra tweaks or special knowledge to use it:

- run tests
- inspecting and debugging problems
- enhancing tests
- login to a test system

## Steps to Reproduce

1. Use the steps described in ""Development"

## Environment
 - latest module release
 - Ubuntu 18.04
-  Virtualbox 6.0.22-137980~Ubuntu

**Comment by sanfrancrisko** [comment]
@scoopex Thanks for reporting. Looking at the console output, my guess is that your `inventory.yaml` could have had entries from a previously provisioned test run and these containers were torn down using Docker directly or some other manner other than `bundle exec rake litmus:tear_down`

Note the port numbers of the hosts you're provisioning (`2202`, `2203` and `2204`):
```
Provisioning ubuntu/xenial64 using vagrant provisioner.[✔]
127.0.0.1:2202, ubuntu/xenial64
Provisioning debian/stretch64 using vagrant provisioner.[✔]
127.0.0.1:2203, debian/stretch64
Provisioning centos/7 using vagrant provisioner.[✔]
127.0.0.1:2204, centos/7
```
Then the `litmus:install_agent` rake task is trying to SSH to `2222`
```
$ bundle exec rake 'litmus:install_agent[puppet5]'
install_agent
rake aborted!
Installation of agent failed.
Errors: {"127.0.0.1:2222"=>{"kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Failed to connect to 127.0.0.1:2222: Connection refused - connect(2) for 127.0.0.1:2222", "details"=>{}, "issue_code"=>"CONNECT_ERROR"}, "127.0.0.1:2200"=>{"kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Failed to connect to 127.0.0.1:2200: Connection refused - connect(2) for 127.0.0.1:2200", "details"=>{}, "issue_code"=>"CONNECT_ERROR"}, "127.0.0.1:2201"=>{"kind"=>"puppetlabs.tasks/connect-error", "msg"=>"Failed to connect to 127.0.0.1:2201: Connection refused - connect(2) for 127.0.0.1:2201", "details"=>{}, "issue_code"=>"CONNECT_ERROR"}}
```

Could you confirm the contents of the `inventory.yaml` in the module root dir? I suspect this is what has happened, although a confirmation from your side would be much appreciated.

I have run in to this myself the odd time, so I will raise a ticket to determine a way to better handle or alert the user to stale entries in the `inventory.yaml`

**Comment by sanfrancrisko** [comment]
Raised [IAC-888](https://github.com/puppetlabs/puppetlabs-kubernetes/issues/419) should you wish to follow @scoopex

**Comment by scoopex** [comment]
I missed that there is that file, because it is part of the .gitignore file (attached it).
[inventory.yaml.txt](https://github.com/puppetlabs/puppetlabs-kubernetes/files/4782424/inventory.yaml.txt)

Deleted the file an tried it again. Is there a procedure for the teardown of the virtualbox systems that should be part of the documentation?

Same problem appears:
```
$ bundle exec rake 'litmus:install_module'
Built
rake aborted!
Installation of package puppetlabs-kubernetes-5.1.0.tar.gz failed.
Errors: {"127.0.0.1:2222"=>{"kind"=>"puppetlabs.tasks/command-error", "issue_code"=>"COMMAND_ERROR", "msg"=>"The command failed with exit code 127", "details"=>{"exit_code"=>127}}, "127.0.0.1:2200"=>{"kind"=>"puppetlabs.tasks/command-error", "issue_code"=>"COMMAND_ERROR", "msg"=>"The command failed with exit code 127", "details"=>{"exit_code"=>127}}}
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/puppet_litmus-0.18.2/lib/puppet_litmus/rake_helper.rb:362:in `raise_bolt_errors'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/puppet_litmus-0.18.2/lib/puppet_litmus/rake_helper.rb:250:in `block in install_module'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/honeycomb-beeline-2.0.0/lib/honeycomb/client.rb:65:in `start_span'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/puppet_litmus-0.18.2/lib/puppet_litmus/rake_helper.rb:230:in `install_module'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/puppet_litmus-0.18.2/lib/puppet_litmus/rake_tasks.rb:234:in `block (2 levels) in <top (required)>'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/honeycomb-beeline-2.0.0/lib/honeycomb/client.rb:65:in `start_span'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/honeycomb-beeline-2.0.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/home/schoecmc/.rvm/gems/ruby-2.5.1/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/home/schoecmc/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
/home/schoecmc/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => litmus:install_module
(See full trace by running task with --trace)
```
[inventory.yaml.after.delete.txt](https://github.com/puppetlabs/puppetlabs-kubernetes/files/4782503/inventory.yaml.after.delete.txt)

**Comment by sanfrancrisko** [comment]
@scoopex The tear down steps are outlined in the documentation in [step 7 on this page](https://puppetlabs.github.io/litmus/Running-acceptance-tests.html):
```
bundle exec rake litmus:tear_down
```
Deleting the file will work too, but it will mean having to monitor and remove resources manually from Docker / Vagrant / Other provisioning platform. You can do this is you safely know the `inventory.yaml` has been sitting around for a long time and you've deleted the images / containers yourself since then.

That latest error is a different issue - it's with the `install_module` task. Did you run the `install_agent` task **before** running the `install_module` task?

It would also be good to bump Litmus to version `0.18.3` (just fetch from origin and rebase the branch with `origin/master`, then redo a `bundle install`) - this version provides more details in the error messages.

**Comment by scoopex** [comment]
Before writing my last comment i deleted the file and executed the steps exactly in the order like described in the README.
I upgraded to litmus 0.18.3 and reexecuted all the steps without success :-1: (

[fail.txt](https://github.com/puppetlabs/puppetlabs-kubernetes/files/4788829/fail.txt)

I use kitchen for acceptance tests, an i am pretty happy with that :-)
(example https://github.com/scoopex/puppet-hosting_basesetup and https://github.com/scoopex/puppet-kitchen_template)

**Comment by daianamezdrea** [comment]
Hi @scoopex, when I started to test your PRs I encountered the same problem and this is how I solve it:
1.  before install module run this: **bolt task run provision::fix_secure_path --inventory inventory.yaml --targets 127.0.0.1:2222 --modulepath spec/fixtures/modules/**
2. re-run install module
3. if you have more targets you need to apply fix_secure_path for every target

Please try this and tell me if it's working!Cheers!

**Comment by nepomucen** [comment]
Hi @daianamezdrea, the workaround suggested by you worked for me pretty well on ubuntu/xenial64 (Ubuntu 16.04 LTS image for vagrant Provisioner), thanks for it. [](url)
[success_puppet6.txt](https://github.com/puppetlabs/puppetlabs-kubernetes/files/5150359/success_puppet6.txt)
