### ISSUE TITLE
cannot install any version of ETCD except the base 3.2.18

### ISSUE THREAD

**Issue by thaylin** [puppetlabs/puppetlabs-kubernetes#422]
## Describe the Bug
In setting up a new cluster ETCD is not being installed by the defined version but is defaulting to the base version
Jul 13 21:15:44 k8m-d1.[71791]: etcd Version: 3.2.18

## Expected Behavior
install etcd 3.4.9.

## Steps to Reproduce

kubernetes::kubernetes_version: 1.18.5-0
--
  | kubernetes::etcd_version: 3.4.9
  | kubernetes::controller: true
  | kubernetes::etcd_install_method: wget
  | kubernetes::etcd_source: https://storage.googleapis.com/etcd/v3.4.9/etcd-v3.4.9-linux-amd64.tar.gz
  | kubernetes::docker_yum_baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
  | kubernetes::docker_yum_gpgkey: 'https://download.docker.com/linux/centos/gpg'
  | kubernetes::kubernetes_package_version: 1.18.5-0
  | kubernetes::docker_version: 19.03.12-3.el7
  | kubernetes::docker_package_name: docker-ce
  | kubernetes::container_runtime: docker
  | kubernetes::cni_network_provider: https://raw.githubusercontent.com/cilium/cilium/1.4.3/examples/kubernetes/1.10/cilium.yaml
  | kubernetes::cni_pod_cidr: 10.244.0.0/16
  | kubernetes::etcd_initial_cluster: k8m-d1=https://10.76.10.210:2380,k8s-d1=https://10.76.10.211:2380,k8s-d2=https://10.76.10.212:2380,k8m-d2=https://10.76.10.213:2380,k8m-d3=https://10.76.10.214:2380,k8s-d3=https://10.76.10.215:2380
  | kubernetes::etcd_peers:
  | - 10.76.10.213
  | - 10.76.10.214
  | kubernetes::etcd_ip: "%{networking.ip}"
  | kubernetes::kube_api_advertise_address: "%{networking.ip}"
  | kubernetes::api_server_count: 6
  | kubernetes::install_dashboard: true
  | kubernetes::controller_address: 10.76.10.210:6443

## Environment
 - Version 5.1.0
 - Platform RedHat 8
 - Puppet version 5

## Additional Context
journalctl log for etcd:
-- Logs begin at Mon 2020-07-13 16:42:33 EDT, end at Mon 2020-07-13 21:20:40 EDT. --
Jul 13 21:15:44 k8m-d1 systemd[1]: etcd.service: Service RestartSec=5s expired, scheduling restart.
Jul 13 21:15:44 k8m-d1 systemd[1]: etcd.service: Scheduled restart job, restart counter is at 545.
Jul 13 21:15:44 k8m-d1 systemd[1]: Stopped etcd.
Jul 13 21:15:44 k8m-d1 systemd[1]: Starting etcd...
Jul 13 21:15:44 k8m-d1 etcd[71791]: etcd Version: 3.2.18
Jul 13 21:15:44 k8m-d1 etcd[71791]: Git SHA: eddf599c6
Jul 13 21:15:44 k8m-d1 etcd[71791]: Go Version: go1.8.7
Jul 13 21:15:44 k8m-d1 etcd[71791]: Go OS/Arch: linux/amd64
Jul 13 21:15:44 k8m-d1 etcd[71791]: setting maximum number of CPUs to 2, total number of available CPUs is 2
Jul 13 21:15:44 k8m-d1 etcd[71791]: the server is already initialized as member before, starting as etcd member...
Jul 13 21:15:44 k8m-d1 etcd[71791]: peerTLS: cert = /etc/kubernetes/pki/etcd/peer.crt, key = /etc/kubernetes/pki/etcd/peer.key, ca = , trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true
Jul 13 21:15:44 k8m-d1 etcd[71791]: listening for peers on https://10.76.10.210:2380
Jul 13 21:15:44 k8m-d1 etcd[71791]: listening for client requests on 10.76.10.210:2379
Jul 13 21:15:44 k8m-d1 etcd[71791]: name = k8m-d1
Jul 13 21:15:44 k8m-d1 etcd[71791]: data dir = /var/lib/etcd
Jul 13 21:15:44 k8m-d1 etcd[71791]: member dir = /var/lib/etcd/member
Jul 13 21:15:44 k8m-d1 etcd[71791]: heartbeat = 100ms
Jul 13 21:15:44 k8m-d1 etcd[71791]: election = 1000ms
Jul 13 21:15:44 k8m-d1 etcd[71791]: snapshot count = 100000
Jul 13 21:15:44 k8m-d1 etcd[71791]: advertise client URLs = https://10.76.10.210:2379
Jul 13 21:15:44 k8m-d1 etcd[71791]: restarting member 98895ad79f82c8de in cluster 28a5910e8d5fd463 at commit index 10
Jul 13 21:15:44 k8m-d1 etcd[71791]: 98895ad79f82c8de became follower at term 6
Jul 13 21:15:44 k8m-d1 etcd[71791]: newRaft 98895ad79f82c8de [peers: [], term: 6, commit: 10, applied: 0, lastindex: 10, lastterm: 6]
Jul 13 21:15:44 k8m-d1 etcd[71791]: simple token is not cryptographically signed
Jul 13 21:15:44 k8m-d1 etcd[71791]: starting server... [version: 3.2.18, cluster version: to_be_decided]
Jul 13 21:15:44 k8m-d1 etcd[71791]: ClientTLS: cert = /etc/kubernetes/pki/etcd/server.crt, key = /etc/kubernetes/pki/etcd/server.key, ca = , trusted-ca = /etc/kubernetes/pki/etcd/ca.crt, client-cert-auth = true
Jul 13 21:15:44 k8m-d1 etcd[71791]: added member 23bf8a67f4f50e46 [http://10.76.10.213:2380] to cluster 28a5910e8d5fd463
Jul 13 21:15:44 k8m-d1 etcd[71791]: starting peer 23bf8a67f4f50e46...
Jul 13 21:15:44 k8m-d1 etcd[71791]: started HTTP pipelining with peer 23bf8a67f4f50e46
Jul 13 21:15:44 k8m-d1 etcd[71791]: 98895ad79f82c8de as single-node; fast-forwarding 9 ticks (election ticks 10)
Jul 13 21:15:44 k8m-d1 etcd[71791]: started streaming with peer 23bf8a67f4f50e46 (writer)
Jul 13 21:15:44 k8m-d1 etcd[71791]: started streaming with peer 23bf8a67f4f50e46 (writer)
Jul 13 21:15:44 k8m-d1 etcd[71791]: started peer 23bf8a67f4f50e46
Jul 13 21:15:44 k8m-d1 etcd[71791]: added peer 23bf8a67f4f50e46
Jul 13 21:15:44 k8m-d1 etcd[71791]: started streaming with peer 23bf8a67f4f50e46 (stream MsgApp v2 reader)
Jul 13 21:15:44 k8m-d1 etcd[71791]: added member 98895ad79f82c8de [http://10.76.10.210:2380] to cluster 28a5910e8d5fd463
Jul 13 21:15:44 k8m-d1 etcd[71791]: added member bcf6db652ae7a5f6 [http://10.76.10.214:2380] to cluster 28a5910e8d5fd463
Jul 13 21:15:44 k8m-d1 etcd[71791]: starting peer bcf6db652ae7a5f6...
Jul 13 21:15:44 k8m-d1 etcd[71791]: started HTTP pipelining with peer bcf6db652ae7a5f6
Jul 13 21:15:44 k8m-d1 etcd[71791]: started streaming with peer 23bf8a67f4f50e46 (stream Message reader)
Jul 13 21:15:44 k8m-d1 etcd[71791]: started streaming with peer bcf6db652ae7a5f6 (writer)
Jul 13 21:15:44 k8m-d1 etcd[71791]: started streaming with peer bcf6db652ae7a5f6 (writer)
Jul 13 21:15:44 k8m-d1 etcd[71791]: peer 23bf8a67f4f50e46 became active
Jul 13 21:15:44 k8m-d1 etcd[71791]: established a TCP streaming connection with peer 23bf8a67f4f50e46 (stream Message reader)
Jul 13 21:15:44 k8m-d1 etcd[71791]: started peer bcf6db652ae7a5f6
Jul 13 21:15:44 k8m-d1 etcd[71791]: added peer bcf6db652ae7a5f6
Jul 13 21:15:44 k8m-d1 etcd[71791]: set the initial cluster version to 3.0
Jul 13 21:15:44 k8m-d1 etcd[71791]: enabled capabilities for version 3.0
Jul 13 21:15:44 k8m-d1 etcd[71791]: updated the cluster version from 3.0 to 3.4
Jul 13 21:15:44 k8m-d1 etcd[71791]: cluster cannot be downgraded (current version: 3.2.18 is lower than determined cluster version: 3.4)..

Oddly in debug I see [0;36mDebug: Cleanup archive /etcd-v3.4.9-linux-amd64.tar.gz^[[0, however it is still installing the lower version 3.2.18. The server has no repos that can install etcd itself.

**Comment by thaylin** [comment]
Oddly in debug I see [0;36mDebug: Cleanup archive /etcd-v3.4.9-linux-amd64.tar.gz^[[0, however it is still installing the lower version 3.2.18. The server has no repos that can install etcd itself.

**Comment by thaylin** [comment]
@sanfrancrisko or any other developer that an help me out with this?

**Comment by TheMeier** [comment]
I also tried to install etcd from centos extras. It has `EnvironmentFile=-/etc/etcd/etcd.conf` set in the service unit but the module configures /etc/defaultss/etcd

**Comment by TheMeier** [comment]
This issue still is relevant
