### ISSUE TITLE
Changes made to apiserver_extra_arguments doesn't gets applied to a running cluster

### ISSUE THREAD

**Issue by galindro** [puppetlabs/puppetlabs-kubernetes#445]
## Describe the Bug
I need to enable an admission controller on apiserver. To do it, I updated `apiserver_extra_arguments` but puppet just updates the kubeadm config (`/etc/kubernetes/config.yaml`) and not `/etc/kubernetes/manifests/kube-apiserver.yaml`.

## Expected Behavior
Update `/etc/kubernetes/manifests/kube-apiserver.yaml` too, making everything necessary for kube-apiserver service reloads its new configuration.

## Steps to Reproduce
1. Bootstrap a new cluster and make sure that it is functional
2. Add any parameter to apiserver_extra_arguments
3. Run puppet agent -t in one controller node

## Environment
 - Version: 5.1.0
 - Platform: Ubuntu 18.04.5 LTS

**Comment by KlavsKlavsen** [comment]
Same issue here..
