### ISSUE TITLE
Allow using the Puppet docker module to manage Docker configuration, for private registry?

### ISSUE THREAD

**Issue by gigi-at-zymergen** [puppetlabs/puppetlabs-kubernetes#46]
We are already heavy Puppet users and are getting going with trying to use this module to run our own Kubernetes cluster on ec2.  

We have a private docker registry and have previously used the Puppet Docker module to configure Docker on nodes with the `docker::registry` config

I get the following error when I tried to use our standard Docker configuration : 
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Apt::Source[docker] is already declared in file /etc/puppetlabs/code/environments/INFRA_866_kubernetes/modules/docker/manifests/repos.pp:19; cannot redeclare at /etc/puppetlabs/code/environments/INFRA_866_kubernetes/modules/kubernetes/manifests/repos.pp:23 at /etc/puppetlabs/code/environments/INFRA_866_kubernetes/modules/kubernetes/manifests/repos.pp:23:11 on node k8-bootstrap-controller
```
It appears that the Kubernetes module adds the docker apt source here : https://github.com/puppetlabs/puppetlabs-kubernetes/blob/637d828e358f3483e3b822b0575fcd777d4ff8a1/manifests/repos.pp#L22 leading to the conflict. 

Wondering what my best options are for managing the Docker config through Puppet; private registries etc.  I can probably define and slam in place a Docker config.json.  I could also use some guidance on the docker and kubernetes service user configs as well.  Would I put that in a `kubernetes` user home ~/.docker/config.json ?  What linux users does the kubernetes module create/expect and run the processes under ?

**Comment by gigi-at-zymergen** [comment]
I just realized that trying to manage the private registry at the Docker level may be the wrong approach.  I should probably add the registry through kubectl per : https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/.  Would it generally be the best practice to not try and manage any Docker config through puppet and look for kubectl ways to configure?

**Comment by scotty-c** [comment]
@gigi-at-zymergen you should definitely add the registry through kubectl. So there is no Docker configuration Kubernetes needs that the module does not already contain. You can still model the kubernetes commands in Puppet DSL
