### ISSUE TITLE
containerd github release link tweak

### ISSUE THREAD

**Issue by daveoy** [puppetlabs/puppetlabs-kubernetes#468]
## Describe the Bug
the module is trying to get releases in this format: https://github.com/containerd/containerd/releases/download/v1.4.3/containerd-1.4.3.linux-amd64.tar.gz
however the releases are artually stored in this format: https://github.com/containerd/containerd/releases/download/v1.4.3/containerd-1.4.3-linux-amd64.tar.gz

## Expected Behavior
expected to download the containerd release from github

## Steps to Reproduce
1. install OS
2. run puppet with kubernetes::containerd_version: 1.4.3

## Environment
- puppet 7.1
- centos 8
- 
## Additional Context
reall just need to change the release filename, the pathing is mostly correct (this must have changed sometime in their repo) 
containerd-1.4.3.linux-amd64.tar.gz changed to containerd-1.4.3-linux-amd64.tar.gz (note the '-' between semver and linux rather than the '.' which exists in the code now.

**Comment by daveoy** [comment]
i can confirm that kubernetes::containerd_archive: containerd-1.4.3-linux-amd64.tar.gz will work around this issue, but you may want to change the default.

**Comment by danifr** [comment]
I believe this commit https://github.com/puppetlabs/puppetlabs-kubernetes/commit/098ddc59820b3fb3b80c8fd19db5546f44bd5994 fixes this issue

**Comment by daianamezdrea** [comment]
Hi @danifr and @daveoy, the issue was solved, let me know if you need something else. Thank you!
