### ISSUE TITLE
Support for Debian 10/ Ubuntu 18.04 and 20.04

### ISSUE THREAD

**Issue by bitvijays** [puppetlabs/puppetlabs-kubernetes#476]
Dear Puppetlabs Team,

Hope you are doing well and had a good weekend. Happy New Year to you :) Thank you for maintaining puppet modules. They really make our life easier. We do really appreciate the support 👍 

## Use Case

Install Kubernetes on Ubuntu 18.04, 20.04 and Debian 10 using `puppetlabs-kubernetes`.

## Describe the Solution You Would Like
Implement the functionality of installing Kubernetes using `puppetlabs-kubernetes` on `Debian 10` and `Ubuntu 18.04/20.04`

## Describe Alternatives You've Considered
Installing Kubernetes manually.

Yours Sincerely,
bitvijays

**Comment by Azulinho** [comment]
I use this module to manage a multi-node cluster on debian 10.

I had a look through my git history and found this one 'make kubernetes work on debian' that contained these changes,


``
# Docker repo and key as documented in
# https://docs.docker.com/install/linux/docker-ce/debian/
kubernetes::docker_apt_location: 'https://download.docker.com/linux/debian'
kubernetes::docker_apt_repos: 'stable'
kubernetes::docker_apt_release: 'stretch'
kubernetes::docker_key_id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
kubernetes::docker_key_source: 'https://download.docker.com/linux/debian/gpg'

# Overriding kubernetes release, as the fact %{codename} in
# manifests/repos.pp does not compile to a sane value in my setup
kubernetes::kubernetes_apt_release: 'kubernetes-buster'

# Override default docker version as defined in
# spec/classes/packages_spec.rb
# to get a package and work with kubeadm 1.13.5
kubernetes::docker_version: '18.06.3~ce~3-0~debian'
kubernetes::docker_package_name: 'docker-ce'

# Override default etcd version as defined in
# spec/classes/packages_spec.rb
# to work witch kubeadm 1.13.5
kubernetes::etcd_version: '3.2.18'
kubernetes::schedule_on_controller: true
``

**Comment by mcblum** [comment]
@Azulinho I've copied your config for my setup and I cannot get it to work for the life of me! Been a few days of trying now. From what I can tell (I'm a K8s noob) the config files are not actually generated at `/etc/kubernetes/kubelet.conf` nor is the one in /var/lib there.
