### ISSUE TITLE
There is not a default container runtime

### ISSUE THREAD

**Issue by exarkun** [puppetlabs/puppetlabs-kubernetes#49]
The readme says that docker is the default container runtime.  However, configuring a worker without configuring `container_runtime` fails:

```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, Please specify a valid container runtime at /etc/puppetlabs/code/environments/.../modules/kubernetes/manifests/service.pp:72:7 on node ...
```

**Comment by scotty-c** [comment]
@exarkun Are you pulling the module from master or the Forge?

**Comment by exarkun** [comment]
From Forge.

**Comment by scotty-c** [comment]
@exarkun I just pulled the module from the forge. V1.0.0 has the following set in params `container_runtime = 'docker' ` Master on Github this has changed. We have not released that as a supported change yet.

**Comment by scotty-c** [comment]
Release v 1.0.1 has now got `docker` as the default runtime
