### ISSUE TITLE
puppet/kubetool:6.0.0 isn't in hub.docker.com

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#493]
Hi folks,

The puppet/kubernetes 6.0.0 module has been available for a couple days now, but I don't see a corresponding version of the kubetool. Per the documentation, these need to match, so I'm not sure how we deploy 6.0.0 without the tool.

Will puppet/kubetool:6.0.0 be released to hub.docker.com soon? I don't see 5.5.0 there either.

**Comment by danifr** [comment]
Please check again https://hub.docker.com/r/puppet/kubetool/tags?page=1&ordering=last_updated

**Comment by daianamezdrea** [comment]
Hi @vrmerlin, the last the versions were pushed, thank you for opening the issue! Thank you also @danifr for your comment!
