### ISSUE TITLE
How do I safely do a Kubernetes upgrade if I'm using puppetlabs-kubernetes?

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#508]
## Use Case

I have successfully this puppetlabs-kubernetes module, version 6.0.0, to deploy Kubernetes 1.20.4. It went smoothly and the cluster is behaving well.

But, Kubernetes 1.20.6 and now even 1.21.0 releases are out. What is the process for smoothly upgrading a cluster to those versions, using this module?

## Describe the Solution You Would Like
Documentation additions that explain how I keep our Kubernetes up to date, while still leveraging this module. What is the process?

**Comment by vrmerlin** [comment]
Is there no answer to this? I asked this question a year go, and also received no answer. It seems to me a process for doing safe upgrades is really critical.

**Comment by danifr** [comment]
+1 for visibility. Also interested in this :+1: Thanks

**Comment by peteroruba** [comment]
Same here

**Comment by ashish1099** [comment]
I have tried this manually, next upgrade I will try to do it from puppet, since this was learning so wanted to see what all I'm going to touch while upgrading the k8s

https://gist.github.com/ashish1099/8fd2a7a1905c3709558f51ce7d39e355
