### ISSUE TITLE
class kubernetes::kube_addons continues to execute the Exec['Install cni network provider'] even if calico is installed, because is in a namespace other than calico-system.

### ISSUE THREAD

**Issue by gaure** [puppetlabs/puppetlabs-kubernetes#513]
## Describe the Bug
class kubernetes::kube_addons continues to execute the Exec['Install cni network provider'] even if calico is installed, because is in a namespace other than calico-system.

## Expected Behavior
Kubernetes masters Exec['Install cni network provider']  properly detects calico daemon set namespace.

## Steps to Reproduce
1. Upgrade from module version 5.0.1 to module 6.0.0
2. Run the puppet agent.

## Environment
 - Version [6.X]
 - Platform [Centos 7]

## Additional Context
The Exec['Install cni network provider'] will run forever because previous puppet modules install calico in the kube-system namespace instead of calico-system.
Please perform the command with --all-namespaces, to avoid future problems.

**Comment by danifr** [comment]
I think this issue was solved by https://github.com/puppetlabs/puppetlabs-kubernetes/pull/511
I cannot reproduce it anymore

**Comment by jadestorm** [comment]
We had to change:
kubernetes::cni_provider: 'calico'
to
kubernetes::cni_provider: 'calico-tigera'
(after #511 mentioned above)
That fixed this issue for us.
