### ISSUE TITLE
Use without kubetool / dynamically gernerate certs / keys

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#52]
The use of the module seems to be based on the assumption that kubetool or some other method will be used to generate certs and keys in advance of the master nodes being built AND that the IP addresses of the masters are known at that point so they can be baked in.

This approach does not work in our Puppet Enterprise environment because I have no control over the IP addresses my nodes will assigned by IPAM. It would also not be viable to run kubetool to update hiera.yaml directly on the nodes.

**Comment by scotty-c** [comment]
@nickperry Thanks for opening the issue. I would imagine that in your case at provisioning time you would have a higher level tool that would orchestrate the creation of the certs. This could be something like Jenkins, Then you could request the ip from IPAM.

**Comment by nickperry** [comment]
Thanks @scotty-c. I've taken care of it for the time being by using wildcard certs and using an fqdn (covered by the wildcard) as the bootstrap ip. It's a good enough approach for what I need at the moment.

**Comment by TJM** [comment]
We workaround this issue by configuring the node at provisioning time to only apply our "base" role on the masters. Once they are built, we have the hostnames and IP addresses to make the SSL certs with kubetool, update hieradata, then change the role to kubernetes.

~tommy
