### ISSUE TITLE
Procedure for adding new controller nodes/etcd into existing cluster.

### ISSUE THREAD

**Issue by bdowling** [puppetlabs/puppetlabs-kubernetes#536]
## What you expected to happen?

I would like to be able to add additional control nodes into an existing cluster (increase from 3 to 5).    I have searched around, but have not found a documented procedure for this.

e.g. does kubetool support creating certs for the new nodes?

How are the existing nodes updated to accept the new members.

If this is possible and documentation exists, please point me to it.

Thanks!

**Comment by puetzp** [comment]
I don't think that is possible right now using `kubetool`, as it would also generate a new Etcd CA and Kube CA and sign the new node certificates using those:

```Ruby
class Kube_tool
  def build_hiera(hash)
    OtherParams.create( hash[:os], hash[:version], hash[:container_runtime], hash[:cni_provider], hash[:cni_provider_version], 
    hash[:etcd_initial_cluster], hash[:etcd_ip], hash[:kube_api_advertise_address], hash[:install_dashboard])
    PreChecks.checks
    CreateCerts.etcd_ca
    CreateCerts.etcd_clients
    CreateCerts.etcd_certificates( hash[:etcd_initial_cluster])
    CreateCerts.kube_ca
    CreateCerts.kube_front_proxy_ca
    CreateCerts.sa    
    CleanUp.remove_files
    CleanUp.clean_yaml( hash[:os])
  end
end
```

Thus the "old" and new control plane nodes would not be able to connect.
