### ISSUE TITLE
Update camptocamp-kmod to puppet-kmod

### ISSUE THREAD

**Issue by sazzle2611** [puppetlabs/puppetlabs-kubernetes#538]
This module has been taken over so puppet now complains about missing dependency since we needed to change the module in order to upgrade it as it was dependency for another module.

**Comment by bastelfreak** [comment]
@sazzle2611 could you provide a PR that updates the name? https://github.com/puppetlabs/puppetlabs-kubernetes/blob/main/metadata.json#L32-L33 and https://github.com/puppetlabs/puppetlabs-kubernetes/blob/main/.fixtures.yml#L9

**Comment by bitvijays** [comment]
@sazzle2611 @bastelfreak 

Would it be a good idea to update the dependencies version also? 

```
root@puppet:~# puppet module list
Warning: Module 'herculesteam-augeasproviders_core' (v3.1.0) fails to meet some dependencies:
  'puppetlabs-kubernetes' (v6.3.0) requires 'herculesteam-augeasproviders_core' (>= 2.1.0 < 3.0.0)
Warning: Module 'puppet-archive' (v6.0.2) fails to meet some dependencies:
  'puppetlabs-kubernetes' (v6.3.0) requires 'puppet-archive' (>= 2.0.0 < 5.0.0)
Warning: Module 'puppetlabs-stdlib' (v7.1.0) fails to meet some dependencies:
  'puppet-kmod' (v3.0.0) requires 'puppetlabs-stdlib' (>=4.13.1 < 7.0.0)
Warning: Missing dependency 'camptocamp-kmod':
  'puppetlabs-kubernetes' (v6.3.0) requires 'camptocamp-kmod' (>= 2.2.0 < 3.0.0)
/etc/puppetlabs/code/environments/production/modules
├── hardening-os_hardening (v2.3.2)
├── herculesteam-augeasproviders_core (v3.1.0)  invalid
├── herculesteam-augeasproviders_sysctl (v2.6.2)
├── puppet-archive (v6.0.2)  invalid
├── puppet-kmod (v3.0.0)
├── puppetlabs-apt (v8.3.0)
├── puppetlabs-docker (v4.1.2)
├── puppetlabs-kubernetes (v6.3.0)
├── puppetlabs-motd (v6.1.0)
├── puppetlabs-ntp (v9.1.0)
├── puppetlabs-powershell (v5.0.0)
├── puppetlabs-pwshlib (v0.10.1)
├── puppetlabs-reboot (v4.1.0)
├── puppetlabs-registry (v4.0.1)
├── puppetlabs-stdlib (v7.1.0)  invalid
└── stahnma-epel (v2.0.0)
```

- `puppet-stdlib` is at version `8.1.0`

**Comment by sazzle2611** [comment]
@bastelfreak @bitvijays 

Should I update the puppet-archive dependency to < 6.0.0 or < 7.0.0 as v6.0.0 drops support for Ubuntu 16.4. It is EoL but it is supported by this module

**Comment by sazzle2611** [comment]
Sorry just realised that it doesn't matter as previous versions can still be used

**Comment by sazzle2611** [comment]
I've created PR https://github.com/puppetlabs/puppetlabs-kubernetes/pull/539

This is the first one I've ever done so hopefully I've done it right!!

**Comment by bitvijays** [comment]
@sazzle2611 Hope you are doing well. Thank you for your pull and merge request. Probably this could be closed now?

**Comment by sazzle2611** [comment]
@bitvijays yes, thank you very much!
