### ISSUE TITLE
Using `puppet module install puppetlabs-kubernetes` on puppet server installs version 0.1.0

### ISSUE THREAD

**Issue by bitvijays** [puppetlabs/puppetlabs-kubernetes#543]
## Describe the Bug
Using `puppet module install puppetlabs-kubernetes` on puppet server installs version 0.1.0

```
root@puppet:~# puppet module install puppetlabs-kubernetes
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Module puppetlabs-kubernetes 0.1.0 is already installed.
```

## Expected Behavior
Latest version to be installed.

Currently, latest version has to be installed via 

```
puppet module install puppetlabs-kubernetes --version 6.3.0
```

## Steps to Reproduce

Install the `puppetlabs-kubernetes` module

```
puppet module install puppetlabs-kubernetes
```

**Comment by bastelfreak** [comment]
based on you output the command doesnt install 0.1.0, 0.1.0 is already installed. `puppet module install` does not upgrade an existing module. please try `puppet module upgrade` or tools like r10k.

**Comment by bitvijays** [comment]
Thanks @bastelfreak :) Closing the issue.
