### ISSUE TITLE
Support archive installation of kubernetes components

### ISSUE THREAD

**Issue by daveoy** [puppetlabs/puppetlabs-kubernetes#550]
## Use Case
i have an air-gapped environment where i can't update package repos, so i'd like to be able to pull kubelet, kubeadm and kubectl from a tarball

## Describe the Solution You Would Like
provide hieradata that describes where to find the various parts needed to manually install kubeadm components as describe here: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl (under "Without a Package Manager")

## Describe Alternatives You've Considered
packages work well under normal circumstances, but i can't manage our repos at my org, and we already allow archive / wget install methods for etcd, containerd, runc etc -- why not kubeadm?

## Additional Context
i have provided a PR i have tested for this, will add in the comments

**Comment by daveoy** [comment]
[PR here](https://github.com/puppetlabs/puppetlabs-kubernetes/pull/551)

**Comment by SimonHoenscheid** [comment]
best practice in this case would be running a local mirror. The packages are just the starting point, during the setup process kubernetes will start pulling containers. so you will need a local registry like harbor too.

**Comment by daveoy** [comment]
we are running a local mirror for the containers, that's a given in my scenario. providing containers to the cluster is outside the scope of this module anyways so im sorry @SimonHoenscheid  but im not sure how your comment is relevant to this issue or the linked PR

**Comment by daveoy** [comment]
@SimonHoenscheid how can we get this merged?

I am using the referenced for in an air-gapped environment right now, and have been since the fork was established. it works well.

**Comment by daveoy** [comment]
this issue and it's associated PR is not complete
