### ISSUE TITLE
Support for RedHat derivatives version 8 and 9

### ISSUE THREAD

**Issue by TheMeier** [puppetlabs/puppetlabs-kubernetes#563]
## Use Case
Currently `metadata.json` only lists CentOS 7 as supported OS. Since 2020-08-06 CentOS 7 only receives maintenance update, it will receive no updates at all after 2024-06-30.

## Describe the Solution You Would Like
This module should support RedHat 8 and 9 and their "clones" (Alma Linux, Rocky Linux)

**Comment by deric** [comment]
@TheMeier You're right, RedHat should be listed as supported OS. Though Google doesn't seem to have a release for RedHat 8 and 9 in their [Yum repo](https://packages.cloud.google.com/yum/repos/) yet.

**Comment by jordanbreen28** [comment]
Closing this issue as support was added in https://github.com/puppetlabs/puppetlabs-kubernetes/issues/563.
