### ISSUE TITLE
Calico install doesn't work

### ISSUE THREAD

**Issue by mmoore0011** [puppetlabs/puppetlabs-kubernetes#584]
## Describe the Bug
Calico doesn't install using this module.  I suspect there was a change in the install procedure on caloco's end.  See https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises

## Expected Behavior
Calico installs

## Steps to Reproduce
Use the module with the calico option.  You'll get the error

```
Error: 'kubectl apply -f https://docs.projectcalico.org/archive/3.18/manifests/calico.yaml' returned 1 instead
 of one of [0]                                                                                                
Error: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]/returns: change from 'notrun' t
o ['0'] failed: 'kubectl apply -f https://docs.projectcalico.org/archive/3.18/manifests/calico.yaml' returned 
1 instead of one of [0] (corrective) 
```

that url is now a redirect but even the redirect generates a 404.  Doesn't seem to matter which version of calico I specify.

**Comment by pmcmaw** [comment]
Hey @mmoore0011 can you please give me additional information on the version of the module you are currently using?

**Comment by ashish1099** [comment]
it fails with 3.25 as well and need a `--server-side` in the apply command as well, I'm using the latest k8s puppet module

**Comment by r-tierney** [comment]
i got this working in my PR:
https://github.com/puppetlabs/puppetlabs-kubernetes/pull/625
