### ISSUE TITLE
Containerd won't bind GRPC endpoint

### ISSUE THREAD

**Issue by deric** [puppetlabs/puppetlabs-kubernetes#596]
After socket change introcuded in #576 containerd is biding only `/run/containerd/containerd.sock.ttrpc` socket.

`/run/containerd/containerd.sock` is not binded.

current behavior
```bash
$ ls -laF /run/containerd/containerd.sock*
srw-rw---- 1 root root 0 Dec 10 12:16 /run/containerd/containerd.sock.ttrpc=
```
expected behavior:

```
$ ls -laF /run/containerd/containerd.sock*
srw-rw---- 1 root root 0 Dec 10 12:23 /run/containerd/containerd.sock=
srw-rw---- 1 root root 0 Dec 10 12:23 /run/containerd/containerd.sock.ttrpc=
```

This causes `kubelet` to report `NotReady` status.

## Environment
 - containerd 1.6.6
 - Debian 11
 - puppetlabs-kubernetes main branch ref [7238ba0](https://github.com/puppetlabs/puppetlabs-kubernetes/commit/7238ba0156e1c1b97fe3e382b2cc6e97ddfce758)

**Comment by deric** [comment]
cc @chelnak

**Comment by chelnak** [comment]
Hey @deric - I came to the same conclusion earlier today. 

I'm going to revert the change in that PR and continue trying to get our main branch back in a better state.
