### ISSUE TITLE
Non-RFC1918 addressing used for weave pod networking - typo?

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#62]
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/b55e5cfe60e8bccdb518a79981444a59a3d3391b/tooling/kube_tool/other_params.rb#L18

Is this a typo and the IPALLOC_RANGE should be 10.32.0.0/12 not 100.32.0.0/12?

**Comment by davejrt** [comment]
@nickperry This address space was used to work around conflicts experienced on some virtual infrastructure and weave not starting correctly as a result. It was purposefully done, however can obviously be changed to suit your individual environment by removing the `\&env.IPALLOC_RANGE=100.32.0.0/12` portion of the value

**Comment by nickperry** [comment]
OK, I can see that. It's feels kinda wrong though doing reverse resolution of pod IPs and getting answers for  verizon broadband addressing. I guess it wouldn't pose a real problem unless you actually tried to connect from a pod to a service hosted in the real 100.32.0.0/12.

**Comment by cbricart** [comment]
maybe that's meant to be some /12 within 100.64.0.0/10 instead - which would be https://tools.ietf.org/html/rfc6598 addressing..?
