### ISSUE TITLE
Version bump for puppet/kubetool ?

### ISSUE THREAD

**Issue by r-tierney** [puppetlabs/puppetlabs-kubernetes#632]
## Describe the Bug

[The Docs for puppetlabs/kubernetes](https://forge.puppet.com/modules/puppetlabs/kubernetes/readme#generating-the-module-configuration) indicate to use the same version of puppet/kubetool as puppetlabs-kubernetes

> Note:: The version of Kubetool you use must match the version of the module on the Puppet Forge. For example, if using the module version 1.0.0, use puppet/kubetool:1.0.0.

However the latest version of puppet/kubetool is 7.0.0 [link](https://hub.docker.com/r/puppet/kubetool/tags)
and the latest version or puppetlabs/kubernetes is 7.1.0 [releases link](https://github.com/puppetlabs/puppetlabs-kubernetes/releases)

I found using puppetlabs/kubernetes is 7.1.0 works with puppet/kubetool is 7.0.0 but figured i'd raise this anyway

**Comment by jordanbreen28** [comment]
@r-tierney thanks for spotting this!!
I've pushed puppet/kubetool:7.1.0 and is available on docker hub [here](https://hub.docker.com/r/puppet/kubetool/tags).

**Comment by r-tierney** [comment]
I think kubetool needs another version bump for the latest 8.0.0 release
