### ISSUE TITLE
Version bump for kubetool?

### ISSUE THREAD

**Issue by r-tierney** [puppetlabs/puppetlabs-kubernetes#643]
## Describe the Bug

[The Docs for puppetlabs/kubernetes](https://forge.puppet.com/modules/puppetlabs/kubernetes/readme#generating-the-module-configuration) indicate to use the same version of puppet/kubetool as puppetlabs-kubernetes

> Note:: The version of Kubetool you use must match the version of the module on the Puppet Forge. For example, if using the module version 1.0.0, use puppet/kubetool:1.0.0.

However the latest version of puppet/kubetool is 7.1.0 [link](https://hub.docker.com/r/puppet/kubetool/tags)
and the latest version or puppetlabs/kubernetes is 8.0.0 [releases link](https://github.com/puppetlabs/puppetlabs-kubernetes/releases)

**Comment by jordanbreen28** [comment]
Hey @r-tierney, thank you for raising this with us, again!! 
I had hoped the work to automate this as part of our release process would have been done, so let me see if I can get a higher priority on that to stop this happening again!

Meanwhile I'll work on getting both v7.1.1 and v8.0.0 of the kubetool image published.

**Comment by jordanbreen28** [comment]
Hey @r-tierney, thats both v7.1.1 and v8.0.0 of the kubetool image published.
Thanks for raising this, and hopefully this should not happen again.
