### ISSUE TITLE
Unavailable default version for kubernetes-cli/wrong default version for kubernetes-cni

### ISSUE THREAD

**Issue by itilitymaarten** [puppetlabs/puppetlabs-kubernetes#66]
I'm trying to set up a kubernetes cluster using this puppet module, but I've run into an error: `Version '0.5.1-01' for 'kubernetes-cni' was not found`. When checking apt (using `apt search kubernetes-cni`), it indeed shows that only version 0.6.0 is known.

The readme indicates that 0.5.1 is the default, and the actual values in params.pp say 0.5.1-01 (I'm running on Ubuntu 16.04). However, the documentation in init.pp says the default value should be 0.6.0. Why is there this mismatch?

Assuming 0.6.0 is the correct version to use, I can fix my issue, but still the documentation should match the actual manifests.

EDIT: my statement about the documentation wasn't entirely accurate; fixed

**Comment by davejrt** [comment]
@itilitymaarten I'll have a look at this and see where we need to make any changes to the doco

**Comment by scotty-c** [comment]
fixed in #67
