### ISSUE TITLE
scheduler_extra_arguments not working on v1beta3 due to missing scheduler_merged_extra_arguments used in the template

### ISSUE THREAD

**Issue by catalinpan** [puppetlabs/puppetlabs-kubernetes#669]
## Describe the Bug
**scheduler_extra_arguments** for **v1beta3** doesn't pick up the values as the template uses **scheduler_merged_extra_arguments** which is not specified anywhere other than in the template.

https://github.com/puppetlabs/puppetlabs-kubernetes/blob/02aa06d0dc451c8ddf23e4fc18f938dff767d685/templates/v1beta3/config_kubeadm.yaml.erb#L87-L92

## Expected Behavior
scheduler_extra_arguments should populate the extraArgs values in /etc/kubernetes/config.yaml

It looks like in  https://github.com/puppetlabs/puppetlabs-kubernetes/blob/02aa06d0dc451c8ddf23e4fc18f938dff767d685/manifests/config/kubeadm.pp 

below part (or something similar) is missing 

$scheduler_merged_extra_arguments = concat($scheduler_extra_arguments, $cloud_args)

## Steps to Reproduce
In a kubernetes cluster > 1.21 add scheduler_extra_arguments. The scheduler extraArgs will not be populated.

For more details please check this part of the kubeadm manifest.
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/02aa06d0dc451c8ddf23e4fc18f938dff767d685/manifests/config/kubeadm.pp#L348-L381

## Environment
 - Version 1.23.10
 - Platform Ubuntu 22.04

## Additional Context
n/a

**Comment by deric** [comment]
This should have been fixed in #670, could you test the fix from the `main` branch?

**Comment by catalinpan** [comment]
Thanks, it seems to work.
