### ISSUE TITLE
Kube-proxy configured to be using proxy-mode = userspace and a really old version

### ISSUE THREAD

**Issue by mrwulf** [puppetlabs/puppetlabs-kubernetes#78]
This is less of a feature request or bug report and more of a question of intent...
I noticed the `kube-proxy-daemonset` that gets created by this project is using a really old version (1.6.6) and is hardcoded to the userspace mode. Neither of these is the default and I couldn't find any reasoning behind configuring it this way.

Why isn't the `kube-proxy` version independent? (like `kube-dns-daemonset`)

Why is the proxy-mode set to userspace?

Thanks for the nice module!

**Comment by scotty-c** [comment]
@mrwulf The userspace mode is set for backwards compatibility to 1.6 I am working on adding Calico support now. This will also fix the issue of the kube proxy versioning not available as a param

**Comment by nickperry** [comment]
I can't get any traffic to reach a destination pod via kube-proxy services in my puppetlabs-kubernetes module built 1.9.3 cluster (weave pod networking). However, I have no such problems on my kubeadm built clusters (also 1.9.3 with weave pod networking). They're using iptables mode:

   kube-proxy:                                              
    Image:  gcr.io/google_containers/kube-proxy-amd64:v1.9.3
    Port:   <none>                                          
    Command:                                                
      /usr/local/bin/kube-proxy                             
      --config=/var/lib/kube-proxy/config.conf              
    Environment:  <none>                                    
    Mounts:                                                 
      /lib/modules from lib-modules (ro)                    
      /run/xtables.lock from xtables-lock (rw)              
      /var/lib/kube-proxy from kube-proxy (rw)

**Comment by mrwulf** [comment]
I've added a PR that removes the explicit parameter, but allows you to specify the kube-proxy version. I did some testing (albeit only with newer versions of k8s) and couldn't notice/measure and difference between userspace or iptables modes. Nearly everyone uses iptables mode these days though, so default == better.

**Comment by scotty-c** [comment]
@mrwulf As mentioned above we need to be able to support older versions of K8 as well. I am working internally on what that model looks like and how it affects the code base. I don't want `if version` throughout the code. It will just not scale.

**Comment by scotty-c** [comment]
@nickperry I have just tested the module on 1.9.4 with Weave and was able to install consul and hit the service. Can you open a separate issue? I am keen to see whats happening there. I don't want it to take over this issue. 

Thanks in advance

**Comment by mrwulf** [comment]
PR #82 is in now and allows a custom kube-proxy version. `proxy-mode=userspace` was removed so the proxy mode will be whatever the default is for that version. Pick a version with the default proxy-mode of iptables (or eventually ipvs) if you want something else.
