### ISSUE TITLE
Add support for adding additional pki certificate files

### ISSUE THREAD

**Issue by nickperry** [puppetlabs/puppetlabs-kubernetes#80]
**  FEATURE REQUEST **

We need to be able to manage addtional PKI certs under /etc/kubernetes/pki, beyond those currently defined in config.pp's $kube_pki_files,

Our immediate use-case is to add a CA cert for our OIDC auth server. The module gives us the flexibility to tell kubernetes where the OIDC CA file should be (by adding --oidc-ca-file=/etc/kubernetes/pki/dex-ca.crt to kubernetes::apiserver_extra_arguments), but I cannot create the certificate on disk.

Currently, if I add a file resource for '/etc/kubernetes/pki/dex-ca.crt' outside of the module, I will get a dependency cycle error.

  file{'/etc/kubernetes/pki/dex-ca.crt':
    ensure  => file,
    content => $dex_ca_crt
  } ->

  class {'kubernetes':
    bootstrap_controller_ip => $bootstrap_controller_ip,
    controller              => true,
    bootstrap_controller    => true,
  }

Error: Failed to apply catalog: Found 1 dependency cycle:
(File[/etc/kubernetes/] => File[/etc/kubernetes/pki] => File[/etc/kubernetes/pki/dex-ca.crt] => Class[Kubernetes] => Class[Kubernetes::Config] => File[/etc/kubernetes/])

Because we have configured kubernetes (via kubernetes::apiserver_extra_arguments) to use OIDC auth, it must able to retrieve and validate the OIDC provider's cert. It needs the CA file on disk to be able to do this. Without it, the API server cannot start.

**Comment by nickperry** [comment]
Currently getting by with:

  File <| title == '/etc/kubernetes/pki' |> {
  } ->

  file{'/etc/kubernetes/pki/dex-ca.crt':
    ensure  => file,
    content => hiera('profile_kubernetes::dex_ca_crt')
  }

  class {'kubernetes':
    bootstrap_controller_ip => $bootstrap_controller_ip,
    controller              => true,
    bootstrap_controller    => true,
  }

**Comment by scotty-c** [comment]
@nickperry This is an interesting one. Let me think of a way we can add it to the module neatly. I will update this issue when I have some ideas and run it past you.

**Comment by Zetten** [comment]
This should be made possible by #89 which solves the same problem in my environment.

In my case I want the system CA bundles, since my dex server is exposed with a Let's Encrypt certificate, so I need to fix the broken symlinks from my host's `/etc/ssl/certs`. But mounting a specific dir/file would be possible too.

**Comment by gennady-voronkov** [comment]
sorry for silly question, but where do you take this params - bootstrap_controller_ip, bootstrap_controller.
i have not seen this params in kubernetes classes

**Comment by nickperry** [comment]
@gennady-voronkov they were from an old version of the module.

**Comment by davejrt** [comment]
Closing as this was made possible in #89
