### ISSUE TITLE
kubernetes Module that support  puppet 5 ?

### ISSUE THREAD

**Issue by puppetlabs-kubernetes** [puppetlabs/puppetlabs-kubernetes#85]
Does this module ( kubernetes ) supports Puppet 5, I want to confirm since I see supports Puppet >= 4.2.1 < 5.0.0?  however do you have any kubernetes module that support puppet 5 

Thank you 

Erian 
```

**Comment by scotty-c** [comment]
@puppetlabs-kubernetes This module does support Puppet 5. On the next release, we will changes the metadata.json to reflect that.
