### ISSUE TITLE
Basic install of Kubernetes failing for me

### ISSUE THREAD

**Issue by vrmerlin** [puppetlabs/puppetlabs-kubernetes#95]
## What you expected to happen?

I expected the module to do a basic installation, given the following:

## What happened?
I got this error:

```
# puppet apply --modulepath modules:site manifests/dev_nodes.pp
Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Kubernetes]:
  parameter 'kube_dns_ip' expects a String value, got Undef
  parameter 'kube_api_service_ip' expects a String value, got Undef 
```

## How to reproduce it?

I didn't change anything from the basic example given by the documentation:

```
  class { 'kubernetes':
    controller => true,
    bootstrap_controller => true,
  }
```

## Anything else we need to know?

This was a fresh system setup, with no previous installation via puppet.

## Versions:
```
$ puppet --version
5.3.5

$ kubectl version
didn't get installed

$ docker version OR crictl version
didn't get installed

$ facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.4",
    major => "7",
    minor => "4"
  },
  selinux => {
    enabled => false
  }
}
```

$ puppet module list
```
mod 'puppet-yum', '2.2.1'
mod 'puppetlabs-mysql', '5.3.0'
mod 'puppet-jira', '3.4.1'
mod 'thewired-bitbucket', '2.2.5'
mod 'puppet-confluence', '3.1.1'
mod 'puppetlabs-java', '2.4.0'
mod 'puppetlabs-docker', '1.1.0'
mod 'puppetlabs-kubernetes', '1.1.0'
mod 'puppetlabs-apt', '4.3.0'
mod 'maestrodev-wget', '1.7.0'
mod 'puppetlabs-apache', '3.1.0'
mod 'puppetlabs-concat', '4.2.1'
mod 'puppetlabs-translate', '1.1.0'
mod 'puppetlabs-stdlib', '4.25.0'
mod 'puppet-staging', '2.2.0'
mod 'puppet-archive', '2.1.0'
mod 'camptocamp-systemd', '1.1.1'
mod 'puppetlabs-inifile', '2.2.0'
mod 'mkrakowitzer-deploy', '0.0.3'
mod 'puppet-mysql_java_connector', '3.0.1'
```

**Comment by AranVinkItility** [comment]
Could you check your generated YAML file? It should contain the following keys:
`kubernetes::kube_api_service_ip: <ip>
kubernetes::kube_dns_ip: <ip>`
I ran into a similar issue when using an older version of the kubetool image.

**Comment by vrmerlin** [comment]
Hmmm, my YAML file does contain that information, but i'm wondering if it's not finding it? Here's what I have:

```
├── data
│   └── kubernetes.yaml
├── environment.conf
├── manifests
│   ├── dev_nodes.pp
│   └── nodes.pp
├── modules
│   ├── (MANYMODULES...)
├── Puppetfile
└── site
    ├── profiles
    │   └── manifests
    │       ├── base.pp
    │       ├── kubernetes
    │           └── master.pp
    └── roles
        └── manifests
            ├── kube_master.pp
```

The file ```site\profiles\manifests\kubernetes\master.pp``` contains the code you see in my first message. Given that, is my ```kubernetes.yaml``` file in the right location? I also tried ```site\profiles\files\kubernetes\kubernetes.yaml``` as well, but that didn't work either.

**Comment by AranVinkItility** [comment]
I'm not that good at Hiera, but my guess is there should be a hiera.yaml in the root of your module. This tells Hiera where it can look for the configuration data. Not sure what the default folders are if you don't have a hiera.yaml. Maybe the docs can help:
https://puppet.com/docs/puppet/5.0/hiera_config_yaml_5.html

**Comment by vrmerlin** [comment]
Ok, i was able to get it to work. Two issues: 1) I needed to create the ```hiera.yaml```  file to point to the the ```kubernetes.yaml``` file, and 2) I was in a "development mode", using ```puppet apply...```, so i needed to add the ```--hiera_config=hiera.yaml``` flag so it could find the configuration file.

Thanks for the help!

**Comment by hussainaphroj** [comment]
Hi, 
I am facing the similar issue for puppet 4.10:
 parameter 'etcd_ca_key' expects a String value, got Undef
  parameter 'etcd_ca_crt' expects a String value, got Undef
  parameter 'etcdclient_key' expects a String value, got Undef
  parameter 'etcdclient_crt' expects a String value, got Undef
  parameter 'etcdserver_crt' expects a String value, got Undef
  parameter 'etcdserver_key' expects a String value, got Undef
  parameter 'etcdpeer_crt' expects a String value, got Undef
  parameter 'etcdpeer_key' expects a String value, got Undef
  parameter 'etcd_peers' expects an

**Comment by SimonHoenscheid** [comment]
Have a look here: You missed this step: https://github.com/puppetlabs/puppetlabs-kubernetes#generating-the-module-configuration

**Comment by hussainaphroj** [comment]
Thank you, Simon. I will try the mentioned step
