### ISSUE TITLE
Kubernetes 1.10:unknown flag: --require-kubeconfig

### ISSUE THREAD

**Issue by micah** [puppetlabs/puppetlabs-kubernetes#98]
Because I have not been able to get the network overlay to work in my configuration, I decided to try 1.10 of kubernetes as the module says it supports 1.6 and newer. 

Unfortunately, on deploy, the following is produced:

```
Apr 24 13:17:57 kubeadmin-vpn kubelet[29590]: F0424 13:17:57.777301   29590 server.go:145] unknown flag: --require-kubeconfig
```

**Comment by AranVinkItility** [comment]
AFAIK Kubernetes 1.10 is not supported by this module yet. Ran into the same issues myself when testing.
Some manifests/templates assume k8s 1.9 is latest and revert to older behavior when there is no match:
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/1.1.0/manifests/packages.pp#L14
https://github.com/puppetlabs/puppetlabs-kubernetes/blob/1.1.0/templates/kubernetes.conf.erb#L3

**Comment by micah** [comment]
Yeah, I agree... its just the README says:

```
This module supports Kubernetes 1.6 and above.
```

so maybe that should be adjusted!

**Comment by scotty-c** [comment]
@micah I have updated the README in master, there is work being carried out for a 2.0 release of the module that will support 1.10.x and above

**Comment by leoncard** [comment]
@scotty-c It's good to know you guys are working a version to support 1.10+, thank you. 
Do you guys have an idea of when it will be released?

**Comment by scotty-c** [comment]
@leoncard Not this week as I am at KubeCon EU, so more likely next week when I get home. There is another person working on it with me. He has also been travelling so we need to sync up. I would say most likely next week or the week after

**Comment by leoncard** [comment]
@scotty-c Nice! Thank you :)
